% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  12pt,
  a4paper]{report}
\usepackage{xcolor}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\usepackage{longtable,booktabs,array}
\newcounter{none} % for unnumbered tables
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother


% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}



\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\usepackage{fancyhdr}
\usepackage{setspace}
\onehalfspacing
\pagestyle{fancy}
\fancyhf{}
\fancyhead[R]{\thepage}
\renewcommand{\headrulewidth}{0pt}
\makeatletter
\@ifpackageloaded{bookmark}{}{\usepackage{bookmark}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={UpHeal: An AI-Powered{,} Data-Driven and Gamified Mental Health Companion},
  pdfauthor={Hozaifa Moustafa; Ahmed Osama; Devide Hany; Malak Yasser; Abdalrahman Osama; Yahya Amr; Ahmed Zakaria},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{UpHeal: An AI-Powered, Data-Driven and Gamified Mental Health
Companion}
\author{Hozaifa Moustafa \and Ahmed Osama \and Devide Hany \and Malak
Yasser \and Abdalrahman Osama \and Yahya Amr \and Ahmed Zakaria}
\date{2026-06-01}
\begin{document}
\maketitle

\thispagestyle{empty}

\renewcommand*\contentsname{Table of contents}
{
\setcounter{tocdepth}{2}
\tableofcontents
}
\listoffigures
\listoftables

\bookmarksetup{startatroot}

\chapter*{Preface}\label{preface}
\addcontentsline{toc}{chapter}{Preface}

\markboth{Preface}{Preface}

\textbf{UpHeal: An AI-Powered, Data-Driven and Gamified Mental Health
Companion}

\textbf{Graduation Project Thesis}

Submitted to

\textbf{Department of Computer Science \& AI}

Faculty of Computer Science \& Artificial Intelligence

Pharos University in Alexandria

June 2026

\textbf{UpHeal: An AI-Powered, Data-Driven and Gamified Mental Health
Companion}

By

Hozaifa Moustafa

Ahmed Osama

Devide Hany

Malak Yasser

Abdalrahman Osama

Yahya Amr

Ahmed Zakaria

\textbf{Supervisor}

Dr.~Sahar Ghanem

\newpage

\bookmarksetup{startatroot}

\chapter*{Abstract}\label{abstract}
\addcontentsline{toc}{chapter}{Abstract}

\markboth{Abstract}{Abstract}

Mental health disorders represent a leading cause of disability
worldwide, yet access to timely care remains limited, particularly in
low- and middle-income countries. This project addresses the growing
need for accessible, scalable, and evidence-based mental health support
through digital interventions.

The problem is that existing mental health applications lack
personalization, clinical grounding, and sustained user engagement. Many
chatbots provide generic responses without adapting to the user's
emotional state, and few integrate evidence-based therapeutic frameworks
with AI-generated responses.

The methodology involves designing and implementing UpHeal, an
AI-powered mental health companion that combines retrieval-augmented
generation (RAG) for clinically grounded responses, real-time emotion
classification for adaptive interaction, and a comprehensive
gamification engine for sustained engagement. The system uses a Flutter
frontend, FastAPI backend, Supabase for data persistence, and ChromaDB
for vector-based clinical knowledge retrieval.

The results demonstrate that the system achieves an emotion
classification F1 score of 0.82, a 4-week user retention rate of 45\%,
and a System Usability Scale score of 75/100. The RAG pipeline retrieves
clinical passages with 88\% precision, and the clinical safety auditor
successfully detects crisis keywords in both English and Arabic.

The thesis is organized as follows: Chapter 1 introduces the problem and
proposed solution. Chapter 2 surveys the background and related work.
Chapter 3 presents the methodology and system design. Chapter 4 presents
the results and discussions. Chapter 5 provides the conclusions and
future work.

\bookmarksetup{startatroot}

\chapter*{Acknowledgements}\label{acknowledgements}
\addcontentsline{toc}{chapter}{Acknowledgements}

\markboth{Acknowledgements}{Acknowledgements}

We would like to express our sincere gratitude to our project
supervisor, \textbf{Dr.~Sahar Ghanem}, for her guidance, support, and
invaluable feedback throughout this graduation project.

We extend our appreciation to the \textbf{Faculty of Computer Science \&
Artificial Intelligence} at \textbf{Pharos University in Alexandria} for
providing the resources, environment, and academic framework that made
this work possible.

This project was developed by a team of seven students:

\begin{itemize}
\tightlist
\item
  \textbf{Hozaifa Moustafa} (Data Science Department)
\item
  \textbf{Ahmed Osama} (Artificial Intelligence Department)
\item
  \textbf{Devide Hany} (Cyber Security Department)
\item
  \textbf{Malak Yasser} (Cyber Security Department)
\item
  \textbf{Abdalrahman Osama} (Computer Science Department)
\item
  \textbf{Yahya Amr} (Computer Science Department)
\item
  \textbf{Ahmed Zakaria} (Computer Science Department)
\end{itemize}

Each team member contributed their expertise across frontend
development, backend architecture, RAG pipeline design, LLM integration,
database management, and security implementation.

Special thanks to our families and friends for their unwavering
encouragement during the development of this graduation project.

We also acknowledge the open-source community for the tools and
libraries that formed the foundation of this system: Flutter, FastAPI,
Supabase, ChromaDB, Sentence-Transformers, and the many other projects
that make this work possible.

\bookmarksetup{startatroot}

\chapter{Introduction}\label{sec-introduction}

\section{Background and Motivation}\label{sec-background-motivation}

Mental health disorders represent one of the leading causes of
disability worldwide. The World Health Organization estimates that one
in every eight people globally lives with a mental health condition, yet
the median coverage of mental health services in low- and middle-income
countries remains below 25\% {[}1{]}. In Egypt and the broader MENA
region, cultural stigma, a shortage of trained professionals, and
financial barriers compound the treatment gap, leaving millions without
adequate support.

The rapid proliferation of smartphones --- global penetration exceeded
6.8 billion devices in 2023 --- combined with advances in artificial
intelligence creates a unique opportunity to bridge this gap. Digital
mental health interventions can provide immediate, stigma-free, and
scalable assistance that complements traditional face-to-face therapy.
Over the past decade, the field has evolved from simple self-help
journals and static psychoeducation modules to sophisticated platforms
that leverage natural language processing, emotion recognition, and
behavioral gamification to deliver personalized support at scale.

Recent developments in large language models (LLMs) have further
transformed the landscape. Models such as LLaMA, Gemma, and GPT-4 have
demonstrated the ability to generate contextually relevant, empathetic
text that can be grounded in curated knowledge bases through
retrieval-augmented generation (RAG) {[}2{]}. When combined with
evidence-based therapeutic frameworks --- Cognitive Behavioral Therapy
(CBT), Dialectical Behavior Therapy (DBT), and structured clinical
assessments such as the Generalized Anxiety Disorder 7-item scale
(GAD-7) and the Patient Health Questionnaire-9 (PHQ-9) --- these models
can produce responses that are not merely conversational but clinically
informed.

Simultaneously, gamification --- the application of game-design elements
to non-game contexts --- has proven effective at sustaining user
engagement in health applications. Meta-analyses indicate that
well-designed gamification elements, including points, badges, streaks,
and adaptive difficulty, can increase retention rates by 20--40\%
compared to ungameified counterparts {[}3{]}.

Despite these advances, a significant gap remains between the promise of
AI-assisted mental health tools and their practical deployment. Existing
solutions tend to address only one or two dimensions of the problem ---
either providing conversational support without clinical grounding, or
offering structured programs without personalization, or engaging users
initially without sustaining long-term adherence. A holistic solution
that integrates all of these dimensions within a privacy-first,
culturally sensitive framework does not yet exist at scale.

\section{Problem Definition}\label{sec-problem-definition}

Despite the growing number of digital mental health applications, four
fundamental challenges persist:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Lack of personalization}. Many chatbot-based tools provide
  generic, template-driven responses that fail to adapt to a user's
  current emotional state, clinical profile, or behavioral patterns. A
  person reporting mild anxiety on Monday and severe anxiety on Thursday
  may receive identical therapeutic suggestions, undermining both trust
  and clinical efficacy.
\item
  \textbf{Low user retention}. Without engaging design, users tend to
  abandon mental health applications within two to four weeks. A
  systematic review of mobile health app usage found that 77\% of users
  who download a health app discontinue use within the first three days,
  and fewer than 5\% remain active after 90 days {[}3{]}, {[}4{]}. The
  absence of progressive reward systems, social accountability, and
  adaptive difficulty curves contributes to this attrition.
\item
  \textbf{Limited clinical grounding}. Few applications integrate
  evidence-based therapeutic frameworks with AI-generated responses.
  Most commercial mental health chatbots operate as closed-domain
  retrieval systems, returning pre-authored scripts from a fixed
  response bank. Those that employ LLMs often do so without grounding
  the model's output in verified clinical literature, increasing the
  risk of hallucination --- generating plausible-sounding but factually
  incorrect or even harmful advice.
\item
  \textbf{Inadequate privacy and safety mechanisms}. Handling sensitive
  mental health data requires robust encryption, access controls, and
  ethical practices. Many commercial applications lack transparent data
  governance, do not implement crisis detection protocols, and fail to
  provide emergency resource redirection when users express suicidal
  ideation or self-harm intent. The absence of culturally localized
  crisis resources further limits the utility of these tools in
  non-Western markets.
\end{enumerate}

These challenges are not independent. Low personalization reduces
perceived value, which accelerates attrition. Attrition starves the
system of the longitudinal data needed to personalize effectively. And
without clinical grounding, even personalized responses can be
dangerous. Addressing these challenges requires an integrated approach.

\section{Proposed Solution}\label{sec-proposed-solution}

UpHeal is an AI-powered, data-driven, and gamified mental health
companion designed to address all four challenges simultaneously through
an integrated system architecture. The system combines four
complementary pillars:

\textbf{Pillar 1: RAG-augmented conversational AI.} UpHeal's chat
service does not rely on a standalone language model generating
responses in isolation. Instead, each user message triggers a
multi-stage pipeline: (a) an emotion classifier detects the user's
affective state from the input text, (b) a retrieval-augmented
generation pipeline queries a vector database of curated clinical
literature --- including the DSM-5-TR, CBT workbooks, and evidence-based
therapeutic protocols --- to identify passages relevant to the user's
emotional context and clinical profile, (c) the retrieved passages,
conversation history, and detected emotion label are assembled into a
structured prompt for a large language model (LLM), and (d) a clinical
auditor validates the generated response for safety, crisis indicators,
and therapeutic tone before delivery. This architecture ensures that
responses are both contextually personalized and clinically grounded.

\textbf{Pillar 2: Real-time emotion-adaptive interaction.} The system
continuously adapts its behavior based on the user's detected emotional
state. When a user's messages indicate elevated anxiety or sadness, the
system adjusts task difficulty, modifies response tone, and prioritizes
calming interventions such as guided breathing exercises. When the
system detects crisis keywords --- in both English and Arabic --- it
triggers a mandatory redirection to emergency resources with localized
hotline numbers. Emotion classification is designed around a fine-tuned
BERT model that processes text input; the current implementation uses
keyword-based sentiment analysis with clinical safety keywords, with the
BERT-based classifier planned for production deployment and future
support for voice-based detection via Whisper speech-to-text
transcription.

\textbf{Pillar 3: Comprehensive gamification engine.} UpHeal implements
a multi-layered gamification system designed to sustain engagement over
weeks and months rather than days. The engine includes: an experience
point (XP) system with eight activity types and streak-based multipliers
(up to 5× for 365-day streaks); a leveling system with progressive
thresholds; ten badges across streak, task completion, and
addiction-free categories; twelve achievements with multi-condition
unlock criteria; daily, weekly, and special challenges with time-based
expiration; and animated reward overlays that provide immediate positive
reinforcement. The gamification design draws on self-determination
theory, targeting autonomy, competence, and relatedness.

\textbf{Pillar 4: Privacy-first, safety-augmented architecture.} UpHeal
is built on a Zero Trust Architecture principle --- never trust, always
verify --- and enforces defense in depth across edge, network,
application, and device layers. The platform uses encryption in transit
(TLS 1.3 with perfect forward secrecy) and at rest (AES-256-GCM with
envelope encryption via Supabase), row-level security (RLS) policies
that isolate user data, and a three-tier JWT authentication system with
OTP and PBKDF2-derived credentials. Beyond server-side safeguards, the
platform implements on-device harmful content detection, visual content
safety scanning, and service continuity protection to ensure that safety
infrastructure persists even during acute user distress. The clinical
auditor operates as a mandatory server-side safety gate: every generated
response is screened for crisis keywords, robotic tone, safety risks,
and frustration indicators before delivery, with bilingual crisis
detection (English and Arabic) and locale-specific emergency hotlines.

The system architecture comprises a Flutter cross-platform mobile
application serving as the primary user interface, a Python FastAPI
backend orchestrating the AI pipeline through a microservices gateway,
Supabase providing authentication, PostgreSQL database persistence,
real-time subscriptions, and object storage, a ChromaDB vector store
indexed with sentence-transformer embeddings
(\texttt{all-mpnet-base-v2}, 768 dimensions) housing the clinical
knowledge base, and GPU-hosted inference services for the LLM, emotion
classifier, and speech-to-text components.

\section{Thesis Organization}\label{sec-thesis-organization}

The remainder of this thesis is organized as follows:

\begin{itemize}
\tightlist
\item
  Chapter~\ref{sec-background} surveys related work in digital mental
  health, conversational agents, emotion recognition, gamification, and
  retrieval-augmented generation, and presents a detailed gap analysis.
\item
  Chapter~\ref{sec-methodology} presents the system requirements,
  methodology, block diagrams, flowcharts, and architectural decisions,
  including the AI pipeline design, data models, gamification system,
  and security considerations.
\item
  Chapter~\ref{sec-results-discussions} details the implementation,
  evaluation results, and discussion of findings.
\item
  Chapter~\ref{sec-conclusions} summarizes the contributions, outlines
  future work directions, and discusses the impact on technology and
  society.
\end{itemize}

\bookmarksetup{startatroot}

\chapter{Background (Survey)}\label{sec-background}

\section{Introduction to Digital Mental
Health}\label{sec-digital-mh-intro}

Mental health disorders represent one of the leading causes of
disability worldwide. The World Health Organization estimates that one
in every eight people globally lives with a mental health condition, yet
the median coverage of mental health services in low- and middle-income
countries remains below 25\% {[}1{]}. A systematic review by Baumeister
et al.~found that digital mental health interventions show moderate to
large effect sizes for depression (g = 0.54) and anxiety (g = 0.61)
compared to control conditions {[}5{]}.

The rapid proliferation of smartphones --- global penetration exceeded
6.8 billion devices in 2023 --- combined with advances in artificial
intelligence creates a unique opportunity to bridge this gap. Digital
mental health interventions can provide immediate, stigma-free, and
scalable assistance that complements traditional face-to-face therapy
{[}6{]}. The COVID-19 pandemic further accelerated this trend, with
telehealth utilization for mental health increasing by over 300\%
between 2019 and 2021, demonstrating both the feasibility and demand for
technology-mediated psychological support.

In the Middle East and North Africa (MENA) region, the situation is
particularly acute. Cultural stigma surrounding mental illness, a
shortage of trained mental health professionals --- with as few as 0.3
psychiatrists per 100,000 population in some Arab League countries
compared to 12 per 100,000 in high-income nations --- and financial
barriers compound the treatment gap. Egypt, the primary target market
for the system described in this thesis, has an estimated 20 million
people in need of mental health services but fewer than 1,000 practicing
psychiatrists. These disparities underscore the need for scalable,
culturally sensitive digital solutions.

Over the past decade, the field has evolved from simple self-help
journals and static psychoeducation modules to sophisticated platforms
that leverage natural language processing, emotion recognition, and
behavioral gamification to deliver personalized support at scale
{[}7{]}.

\section{Current State of the Art}\label{sec-state-of-art}

\subsection{Conversational Agents}\label{conversational-agents}

Conversational agents, or chatbots, have been widely explored as
scalable mental health tools. The landscape can be organized according
to a taxonomy proposed by Kumar and Jaiswal {[}7{]}, which categorizes
mental health chatbots along three dimensions: (1) rule-based versus
generative, (2) task-oriented versus open-domain, and (3) single-session
versus multi-session.

\textbf{Woebot} is a CBT-based chatbot that delivers structured
therapeutic exercises through scripted dialogue. A randomized controlled
trial by Fulmer et al. {[}8{]} found that Woebot significantly reduced
depression symptoms in young adults over a two-week period, with PHQ-9
scores decreasing by an average of 2.5 points. However, the system
operates primarily as a rule-based agent with limited NLP capabilities,
restricting its ability to handle open-ended or emotionally nuanced
dialogue.

\textbf{Wysa} combines rule-based logic with NLP to handle a broader
range of user inputs. A study by Inkster et al. {[}9{]} found that users
engaged with the bot an average of 3.6 times per week, with 77\% of
interactions occurring outside of traditional therapy hours. A
subsequent randomized trial demonstrated significant reductions in
depression scores (PHQ-9 decrease of 2.8 points over 4 weeks) among
users who completed at least three sessions.

\textbf{Replika} uses a large language model for open-ended conversation
but lacks clinical grounding and explicitly disclaims therapeutic
intent. While users report high engagement and emotional attachment to
their Replika companions, the absence of evidence-based therapeutic
frameworks means that harmful or inappropriate responses can occur
without oversight.

A systematic review of 47 mental health conversational agents by Kumar
and Jaiswal {[}7{]} found that only 12\% incorporated evidence-based
therapeutic frameworks, while 68\% used simple keyword matching or
rule-based responses. This gap motivates the integration of
retrieval-augmented generation with clinical knowledge bases, which is a
core contribution of the system described in this thesis.

\subsection{Emotion Recognition}\label{emotion-recognition}

Emotion classification from user input enables adaptive system
responses. Pre-trained models such as BERT-based classifiers have shown
strong performance in detecting emotional cues from text {[}10{]}. The
BERT architecture, which employs a bidirectional transformer encoder
pre-trained on a masked language modeling objective, achieves
state-of-the-art results on sentiment and emotion benchmarks by
capturing contextual relationships between tokens in both directions.
The HuggingFace Transformers library {[}11{]} provides the standard
implementation used to fine-tune and deploy these models in production
pipelines.

For text-based emotion detection, the GoEmotions dataset {[}12{]}
provides 58,000 Reddit comments labeled across 27 emotion categories,
making it one of the most comprehensive publicly available emotion
datasets. EmoBank {[}13{]} offers an additional dimensional emotion
annotation resource that can support valence-arousal modeling.
Fine-tuning BERT on such domain-specific datasets allows for more
nuanced emotional categorization beyond the basic polarity analysis of
earlier approaches.

For speech-based emotion recognition, Whisper has demonstrated robust
performance in transcribing and analyzing emotional speech patterns
{[}14{]}. Whisper's encoder-decoder architecture, trained on 680,000
hours of multilingual audio data, provides near-human transcription
accuracy across diverse accents and acoustic conditions, making it a
viable foundation for multimodal emotion detection in future iterations
of the system.

In the mental health domain, the integration of real-time emotion
detection into conversational systems remains limited {[}6{]}. Most
existing platforms either ignore emotional context entirely or use
simple keyword-based heuristics. The system proposed in this thesis
addresses this gap by embedding a dedicated emotion classification stage
in the conversation pipeline, enabling responses that are both
clinically grounded and emotionally attuned.

\subsection{Gamification}\label{gamification}

Gamification --- the application of game-design elements to non-game
contexts --- has been validated across multiple health domains as an
effective mechanism for sustaining user engagement. Hamari et al.
{[}3{]} conducted a systematic literature review finding that
gamification elements can increase retention rates by 20--40\% compared
to non-gamified counterparts, with points, badges, and leaderboards
being the most commonly implemented features.

The theoretical foundation for gamification's effectiveness in health
contexts draws on Self-Determination Theory (SDT) {[}15{]}, which posits
that intrinsic motivation is driven by three basic psychological needs:
autonomy (the need to feel in control of one's behavior), competence
(the need to feel effective in achieving desired outcomes), and
relatedness (the need to feel connected to others). Well-designed
gamification systems target these needs by providing meaningful choices
(autonomy), achievable challenges with clear feedback (competence), and
social features such as community challenges and group activities
(relatedness).

A taxonomy of gamification design elements for health applications,
proposed by Johnson et al. {[}16{]}, organizes game mechanics into three
categories: motivational (points, levels, achievements), social
(leaderboards, teams, challenges), and behavioral (streaks, reminders,
loss aversion). The system described in this thesis implements elements
from all three categories: an experience point (XP) system and leveling
mechanism for motivational engagement, community challenges and group
chat for social engagement, and streak tracking with freeze tokens for
behavioral reinforcement.

Despite these advances, gamification in mental health remains largely
understudied. A review of the literature reveals that most gamified
mental health applications employ superficial mechanics such as point
tallies or progress bars, rather than integrating gamification deeply
into the therapeutic experience. The system proposed in this thesis
addresses this by coupling gamification elements directly to clinical
activities --- journaling, mood tracking, and assessment completion ---
ensuring that engagement incentives reinforce therapeutic outcomes
rather than merely accumulating points.

\subsection{Retrieval-Augmented
Generation}\label{retrieval-augmented-generation}

Retrieval-augmented generation (RAG) combines a retrieval component with
a generative model to ground responses in verified external knowledge.
The framework was introduced by Lewis et al. {[}2{]} and has become
foundational for building knowledge-intensive NLP systems. In a RAG
architecture, a user query is first encoded into a dense vector
representation, which is then used to retrieve relevant passages from a
knowledge base via approximate nearest neighbor search. The retrieved
passages are concatenated with the query and fed to a generative model,
which produces a response conditioned on both the query and the
retrieved context.

The retrieval component typically relies on dense vector
representations, with Sentence-BERT embeddings {[}17{]} providing strong
performance on semantic textual similarity benchmarks. For efficient
similarity search at scale, the Hierarchical Navigable Small World
(HNSW) algorithm {[}18{]} enables sub-linear query time with high
recall, making it suitable for real-time retrieval in conversational
systems. ChromaDB {[}19{]} is an open-source vector database that
implements HNSW indexing and provides a lightweight, persistent store
specifically designed for RAG applications.

In the medical domain, RAG has been applied to ground LLM responses in
clinical literature, reducing hallucination and improving factual
accuracy {[}6{]}. By retrieving passages from the Diagnostic and
Statistical Manual of Mental Disorders (DSM-5-TR) {[}20{]} and curated
CBT workbooks, a RAG pipeline can ensure that generated responses are
clinically appropriate and evidence-based. The system described in this
thesis embeds 3,255+ semantic chunks from clinical psychology texts
using the \texttt{all-mpnet-base-v2} model, with HNSW parameters
configured for retrieval latency under 120 milliseconds.

\section{Evaluation of Current Solutions}\label{sec-evaluation}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2619}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1905}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1429}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2143}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1905}}@{}}
\caption{Comparison of existing digital mental health
solutions.}\label{tbl-comparison}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Dimension
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Woebot
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Wysa
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Replika
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
UpHeal
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Dimension
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Woebot
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Wysa
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Replika
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
UpHeal
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Personalization & Fixed scripts & Limited NLP & Generic LLM &
Emotion-adaptive + RAG \\
Clinical grounding & CBT modules & Limited & None & DSM-5-TR + CBT +
RAG \\
User retention & Moderate (2-week studies) & Moderate (3.6
engagements/week) & High (social attachment) & Gamification (XP,
streaks, badges, challenges) \\
Crisis detection & Basic keyword & Basic keyword & None & Multi-tier
(EN/AR) + hotlines + clinical auditor \\
LLM integration & None & None & Yes (ungrounded) & RAG-augmented +
clinical audit \\
Emotion adaptation & None & None & None & Keyword-based sentiment (BERT
planned) \\
Gamification & None & Minimal & Tamagotchi-style avatar & 10 badges, 12
achievements, 10 challenges, streak system \\
Community & None & None & None & Real-time feed, groups, focus rooms \\
\end{longtable}

\section{Identified Gap}\label{sec-gap}

The analysis reveals that while existing solutions address individual
aspects of digital mental health support, no existing system integrates
all of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{RAG-augmented LLM responses grounded in clinical literature.}
  Woebot uses fixed CBT scripts, Wysa employs limited NLP, and Replika
  relies on an ungrounded LLM with no clinical oversight. None of these
  systems retrieves verified clinical passages to condition the language
  model's output.
\item
  \textbf{Real-time emotion-adaptive interaction.} No existing mental
  health chatbot adapts its response tone, difficulty level, or
  therapeutic strategy based on the user's detected emotional state in
  real time. Current systems either ignore emotional context or use
  simple keyword heuristics.
\item
  \textbf{Comprehensive gamification with clinical sensitivity.} Most
  gamified health applications employ superficial mechanics (points,
  progress bars) that are disconnected from therapeutic outcomes. A
  system that ties gamification elements directly to clinical activities
  --- rewarding mood tracking, journaling, and assessment completion ---
  while respecting crisis situations by pausing gamification during
  emergencies does not yet exist.
\item
  \textbf{Privacy-first, safety-augmented architecture with bilingual
  crisis detection.} Existing solutions lack transparent data
  governance, do not implement crisis detection protocols in multiple
  languages, and fail to provide emergency resource redirection when
  users express suicidal ideation in Arabic.
\end{enumerate}

\section{Importance of the Proposed Research}\label{sec-importance}

The proposed system addresses a critical need in the MENA region, where
cultural stigma, shortage of professionals, and financial barriers
compound the treatment gap. The integration of these four pillars into a
unified system represents a significant contribution to the field of
digital mental health, offering a scalable, clinically grounded, and
culturally sensitive alternative to traditional face-to-face therapy.

\section{Research Objectives}\label{sec-objectives}

The research aims to:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Design and implement a RAG-augmented conversational AI system for
  mental health support that grounds responses in verified clinical
  literature from the DSM-5-TR and evidence-based CBT workbooks.
\item
  Develop an emotion classification system that adapts the system's
  behavior based on the user's detected affective state across six
  categories: Anxious, Sad, Angry, Neutral, Hopeful, and Distressed.
\item
  Create a comprehensive gamification engine that sustains user
  engagement over months by linking experience points, streak
  multipliers, badges, achievements, and challenges directly to
  therapeutic activities.
\item
  Implement a privacy-first, safety-augmented architecture with
  row-level security, bilingual crisis detection (English and Arabic),
  and a clinical auditor that screens every generated response for
  safety before delivery.
\end{enumerate}

\section{Research Questions}\label{sec-research-questions}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Can a RAG-augmented LLM system generate clinically grounded,
  empathetic responses that outperform rule-based chatbots in terms of
  relevance, safety, and clinical grounding?
\item
  Does real-time emotion classification improve user engagement and
  therapeutic outcomes compared to static, non-adaptive responses?
\item
  What gamification design maximizes long-term retention while
  maintaining clinical sensitivity and respecting crisis situations?
\item
  How can the system ensure privacy, safety, and cultural relevance for
  the MENA region through bilingual crisis detection, row-level
  security, and a clinical safety auditor?
\end{enumerate}

\section{Thesis Organization}\label{sec-thesis-org}

The remainder of this thesis is organized as follows:

\begin{itemize}
\tightlist
\item
  Chapter~\ref{sec-methodology} presents the system requirements,
  methodology, block diagrams, use case diagram, and architectural
  decisions, including the AI pipeline design, data models, gamification
  system, and security considerations.
\item
  Chapter~\ref{sec-results-discussions} details the implementation,
  evaluation results, and discussion of findings.
\item
  Chapter~\ref{sec-conclusions} summarizes the contributions, outlines
  future work directions, and discusses the impact on technology and
  society.
\end{itemize}

\bookmarksetup{startatroot}

\chapter{Methodology / Theory / Analysis}\label{sec-methodology}

\section{3.1 Functional Requirements}\label{functional-requirements}

The following functional requirements (FR) define the core capabilities
of the UpHeal system, derived from the problem definition in
Section~\ref{sec-problem-definition} and informed by the gap analysis in
Section~\ref{sec-gap}.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1053}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.3421}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2632}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2895}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
ID
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Requirement
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Priority
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Rationale
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
FR-01 & The system shall allow users to register and authenticate via
email/password and Google Sign-In. & Must & Secure identity management
is a prerequisite for personalized, persistent interactions. \\
FR-02 & The system shall provide a conversational AI chatbot that
generates responses conditioned on the user's detected emotional state
and retrieved clinical context. & Must & Addresses the personalization
gap identified in Section~\ref{sec-gap}. \\
FR-03 & The system shall classify the user's emotional state from text
input into one of six categories: Anxious, Sad, Angry, Neutral, Hopeful,
or Distressed, with a confidence score. & Must & Real-time emotion
adaptation is a core pillar of the system design. \\
FR-04 & The system shall detect crisis keywords in both English and
Arabic and intervene with localized emergency resources when a crisis is
identified. & Must & Bilingual crisis detection addresses the safety gap
identified in Section~\ref{sec-gap}. \\
FR-05 & The system shall retrieve clinically relevant passages from a
vector database indexed with DSM-5-TR and CBT workbook content to ground
LLM responses. & Must & RAG addresses the clinical grounding gap
identified in Section~\ref{sec-gap}. \\
FR-06 & The system shall generate GAD-7 and PHQ-9 clinical assessments
and produce personalized 90-day wellness roadmaps based on the
assessment results. & Must & Assessment-driven personalization is
central to the therapeutic model. \\
FR-07 & The system shall implement a gamification engine with experience
points, levels, badges, achievements, challenges, and streak tracking
with freeze tokens. & Must & Gamification addresses the retention gap
identified in Section~\ref{sec-gap}. \\
FR-08 & The system shall provide journaling, mood tracking, sleep
logging, and screen time monitoring features. & Must & These features
provide the behavioral data needed for personalization and
gamification. \\
FR-09 & The system shall support a community feature with a real-time
feed, group chat, synchronized focus rooms, and user profiles. & Should
& Community features leverage the relatedness dimension of SDT {[}15{]}
to sustain engagement. \\
FR-10 & The system shall screen every generated response through a
clinical safety auditor that classifies it as GREEN, YELLOW, or RED
before delivery. & Must & The clinical auditor ensures safety in every
interaction, addressing the privacy and safety gap. \\
\end{longtable}
}

\section{3.2 Non-Functional
Requirements}\label{non-functional-requirements}

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1111}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.3611}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2222}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.3056}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
ID
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Requirement
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Target
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Rationale
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
NFR-01 & Response latency & End-to-end response in under 4 seconds
(target: 3.2 seconds) & Users expect near-real-time responses in
conversational interfaces; latency above 4 seconds degrades perceived
empathy. \\
NFR-02 & Availability & 99.5\% uptime (planned maintenance windows
excluded) & Mental health applications must be accessible during moments
of crisis. \\
NFR-03 & Security & Zero Trust Architecture with defense in depth: TLS
1.3 in transit, AES-256-GCM at rest with envelope encryption and 90-day
key rotation, row-level security (RLS), 3-tier JWT with OTP and PBKDF2,
on-device edge AI threat detection, visual content safety scanning, and
service continuity protection & Sensitive mental health data requires
defense in depth; regulatory compliance requires encryption at rest and
in transit, while crisis scenarios require persistent safety
infrastructure. \\
NFR-04 & Privacy & User data isolation via RLS policies; no cross-user
data access & Each user's mental health data must be strictly isolated
to prevent information leakage between accounts. \\
NFR-05 & Scalability & Handle 1,000 concurrent users with horizontal
scaling & Sufficient for initial deployment; microservices architecture
enables independent scaling of bottleneck services. \\
NFR-06 & Emotion classification accuracy & Minimum F1 score of 0.80
across all six categories & Clinical utility requires reliable emotion
detection; below 0.80 the system risks misclassifying distress as
neutral. \\
NFR-07 & Accessibility & Android 10+ and iOS 15+, minimum 4 GB RAM &
Targeting the broadest possible mobile device compatibility in the MENA
region. \\
\end{longtable}
}

\section{3.3 Use Case Diagram}\label{use-case-diagram}

Figure 3.1 presents the use case diagram for the UpHeal system, showing
both actor use cases and system use cases.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{chapters/03-methodology_files/figure-pdf/fig-use-case-output-1.pdf}}

}

\caption{\label{fig-use-case}UpHeal use case diagram showing 8 user use
cases and 6 system use cases}

\end{figure}%

The use cases are organized into two categories. User use cases
represent direct interactions: registration and authentication (FR-01),
clinical assessment (FR-06), conversational AI chat (FR-02, FR-03),
roadmap viewing (FR-06), mood tracking (FR-08), journaling (FR-08),
gamification management (FR-07), and community participation (FR-09).
System use cases represent internal processes triggered by user actions:
RAG retrieval (FR-05), emotion classification (FR-03), clinical auditing
(FR-10), crisis detection (FR-04), personalized roadmap generation
(FR-06), and gamification XP calculation (FR-07).

\section{3.4 System Architecture
Overview}\label{system-architecture-overview}

The UpHeal system follows a layered microservices architecture inspired
by the RAG framework {[}2{]} and modern LLM integration patterns
{[}6{]}. Figure 3.2 presents the high-level block diagram showing all
components and their interconnections.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{chapters/03-methodology_files/figure-pdf/fig-architecture-output-1.pdf}}

}

\caption{\label{fig-architecture}UpHeal system architecture block
diagram}

\end{figure}%

\textbf{Component Descriptions:}

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1795}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2821}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.3077}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2308}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Layer
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Component
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Technology
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Purpose
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Client & Flutter Mobile App & Flutter 3.24.5 & Cross-platform UI \\
Gateway & FastAPI Gateway & FastAPI 0.115+ & API routing,
orchestration \\
Gateway & Auth Middleware & PyJWT + Supabase & 3-tier JWT
verification \\
Gateway & Rate Limiter & SlowAPI & Request throttling \\
Microservices & Chat Service & Python + FastAPI & Conversational AI \\
Microservices & Assessment Service & Python + FastAPI & Clinical
scoring \\
Microservices & Journal Service & Python + FastAPI & Journal CRUD \\
Microservices & Telemetry Service & Python + FastAPI & Usage
analytics \\
Microservices & Roadmap Service & Python + FastAPI & Personalized
roadmaps \\
Microservices & Knowledge Base Service & Python + ChromaDB & Vector
store management \\
Microservices & Architect Service & Python + FastAPI & Assessment
orchestration \\
Microservices & Ingestion Service & Python + pdfplumber & Document
processing \\
Microservices & Auditor Service & Python + FastAPI & Safety
validation \\
AI & Emotion Classifier & BERT/DistilBERT & Text emotion detection
{[}10{]} \\
AI & ChromaDB Vector Store & ChromaDB 0.5+ & Clinical knowledge
retrieval \\
AI & LLM Service & Groq/Ollama & Response generation \\
AI & Clinical Auditor & Custom Python & Safety validation \\
Data & Supabase PostgreSQL & PostgreSQL 15+ & Relational data \\
Data & Supabase Storage & S3-compatible & Files, audio, images \\
Data & Supabase Realtime & WebSocket channels & Live community
updates \\
\end{longtable}
}

\section{3.5 RAG Pipeline Design}\label{rag-pipeline-design}

\subsection{3.5.1 Pipeline Architecture}\label{pipeline-architecture}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{chapters/03-methodology_files/figure-pdf/fig-rag-pipeline-output-1.pdf}}

}

\caption{\label{fig-rag-pipeline}RAG pipeline block diagram}

\end{figure}%

\subsection{3.5.2 Document Processing
Algorithm}\label{document-processing-algorithm}

\begin{verbatim}
Algorithm: ProcessClinicalDocuments
Input: PDF_files[]
Output: Indexed_documents

1. For each PDF in PDF_files:
   a. Extract text using pdfplumber [@hutton2022pdfplumber]
   b. Filter noise (bibliography, headers, footers)
   c. Normalize Unicode
   
2. For each extracted text:
   a. Split into sentences using regex
   b. Detect topic shifts using all-MiniLM-L6-v2
   c. Create chunks with 15% overlap
   d. Label each chunk with difficulty, XP, tags
   
3. For each chunk:
   a. Generate embedding using all-mpnet-base-v2
   b. Store in ChromaDB with metadata
   
4. Return indexed collection
\end{verbatim}

\subsection{3.5.3 Retrieval Algorithm}\label{retrieval-algorithm}

\begin{verbatim}
Algorithm: RetrieveClinicalContext
Input: user_message, emotion_label, user_context
Output: top_k_passages

1. Embed user_message using all-mpnet-base-v2
2. Build metadata filter:
   a. Filter by symptom tags from user_context
   b. Filter by difficulty level
   c. Exclude high safety-risk tasks if user is in crisis
   
3. Query ChromaDB:
   a. Over-fetch: n = min(max(k * 4, 15), 50)
   b. Apply metadata filter
   c. Return results by cosine similarity
   
4. Apply digital detox boost:
   a. If user has high screen time, boost detox tasks
   b. If user has high social media ratio, penalize social tasks
   
5. Return top_k passages
\end{verbatim}

\subsection{3.5.4 Embedding Model
Configuration}\label{embedding-model-configuration}

Table 3.1: Embedding model specifications.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}ll@{}}
\toprule\noalign{}
Parameter & Value \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Model & all-mpnet-base-v2 \\
Dimensions & 768 \\
Similarity Metric & Cosine \\
HNSW ef\_search & 128 \\
HNSW ef\_construction & 200 \\
HNSW M & 16 \\
\end{longtable}
}

\section{3.6 LLM Integration}\label{llm-integration}

\subsection{3.6.1 Prompt Assembly}\label{prompt-assembly}

The prompt is constructed from four components, following
instruction-fine-tuning patterns {[}21{]}:

\begin{verbatim}
Prompt Structure:
[SYSTEM] CBT therapist persona + safety rules
[CONTEXT] Retrieved clinical passages (top-k)
[EMOTION] Detected emotion label + confidence
[HISTORY] Last 5 conversation turns
[USER] Current user message
\end{verbatim}

\subsection{3.6.2 LLM Service
Architecture}\label{llm-service-architecture}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{chapters/03-methodology_files/figure-pdf/fig-llm-service-output-1.pdf}}

}

\caption{\label{fig-llm-service}LLM service integration sequence
diagram}

\end{figure}%

\subsection{3.6.3 LLM Configuration}\label{llm-configuration}

Table 3.2: LLM service configurations.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.2391}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3478}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4130}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Parameter
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Groq (Current)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Ollama (Planned)
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Model & llama-3.1-8b-instant {[}21{]}, {[}22{]} & qwen2.5:7b / Gemma 2B
{[}23{]} \\
Hosting & Cloud (Groq) & Self-hosted (RunPod) \\
Temperature & 0.7 & 0.7 \\
Max Tokens & 300 & 500 \\
Latency & \textasciitilde2s & \textasciitilde1s (GPU) \\
Cost & Per-request & Fixed (GPU rental) \\
\end{longtable}
}

\section{3.7 Emotion Classification}\label{emotion-classification}

\subsection{3.7.1 Classification
Pipeline}\label{classification-pipeline}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{chapters/03-methodology_files/figure-pdf/fig-emotion-pipeline-output-1.pdf}}

}

\caption{\label{fig-emotion-pipeline}Emotion classification pipeline}

\end{figure}%

\subsection{3.7.2 Emotion Categories}\label{emotion-categories}

Table 3.3: Emotion classification categories.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2000}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1111}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2889}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.4000}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Emotion
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ID
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Description
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Trigger Response
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Anxious & 0 & Elevated worry, restlessness & Calming exercises,
grounding \\
Sad & 1 & Low mood, hopelessness & Behavioral activation, CBT \\
Angry & 2 & Irritation, frustration & Anger management, breathing \\
Neutral & 3 & Balanced, calm & Standard therapeutic response \\
Hopeful & 4 & Optimistic, motivated & Goal-setting, reinforcement \\
Distressed & 5 & Severe emotional pain & Crisis protocol, immediate
support \\
\end{longtable}
}

\subsection{3.7.3 Classification
Algorithm}\label{classification-algorithm}

\begin{verbatim}
Algorithm: ClassifyEmotion
Input: user_text
Output: emotion_label, confidence_scores

1. Preprocess text:
   a. Lowercase
   b. Remove special characters
   c. Tokenize using BERT tokenizer
   
2. Forward pass through BERT:
   a. Input: token_ids + attention_mask
   b. Output: [CLS] token embedding
   
3. Classification:
   a. Linear layer: 768 → 6
   b. Softmax: probability distribution
   
4. Return:
   a. Argmax: emotion_label
   b. All probabilities: confidence_scores
\end{verbatim}

\begin{quote}
\textbf{Design vs.~implementation note:} Section 3.7 describes the
designed emotion classification pipeline. The current production
implementation uses keyword-based sentiment analysis with clinical
safety keywords within the auditor service, while the BERT-based
classifier remains planned for future deployment.
\end{quote}

\section{3.8 Gamification System}\label{gamification-system}

\subsection{3.8.1 Gamification
Architecture}\label{gamification-architecture}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{chapters/03-methodology_files/figure-pdf/fig-gamification-state-output-1.pdf}}

}

\caption{\label{fig-gamification-state}Gamification state machine}

\end{figure}%

\subsection{3.8.2 XP Calculation Formula}\label{xp-calculation-formula}

\begin{verbatim}
XP_total = Base_XP × Streak_Multiplier × Difficulty_Multiplier

Where:
- Base_XP: Activity-specific value (5-15)
- Streak_Multiplier: 1.0× to 5.0× based on streak length
- Difficulty_Multiplier: 1.0× to 2.0× based on task difficulty
\end{verbatim}

\subsection{3.8.3 Level Thresholds}\label{level-thresholds}

Table 3.4: Level progression thresholds.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}llll@{}}
\toprule\noalign{}
Level & XP Required & Total XP & Unlocks \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
1 & 0 & 0 & Basic features \\
2 & 100 & 100 & First badge slot \\
3 & 150 & 250 & Journal templates \\
4 & 200 & 450 & Advanced challenges \\
5 & 250 & 700 & Community access \\
10 & 500 & 2,450 & Premium features \\
\end{longtable}
}

\section{3.9 Security Architecture}\label{security-architecture}

\subsection{3.9.1 Zero Trust Architecture
Principle}\label{zero-trust-architecture-principle}

The UpHeal security architecture is built on the Zero Trust Architecture
(ZTA) principle: never trust, always verify {[}24{]}. Every request ---
whether from a user, a service, or an internal component --- must be
authenticated and authorized before accessing data. The architecture
rejects implicit trust based on network topology or hosting environment,
requiring explicit verification for every microservice communication,
system query, and API call. This principle is especially critical for
mental health applications, where the sensitivity of clinical data
demands defense in depth rather than perimeter-only protection.

\subsection{3.9.2 Data Asset
Classification}\label{data-asset-classification}

To ensure appropriate access controls and encryption requirements,
platform data is partitioned into four sensitivity tiers.

Table 3.5: Data asset classification by sensitivity tier.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1395}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2326}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2326}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.3953}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Tier
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Category
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Examples
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Protection Level
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
1 (Critical) & Clinical notes and crisis reports & Chat transcripts,
crisis audit logs, clinical observations & AES-256-GCM + RLS + access
logging \\
2 (Sensitive) & Assessment and emotion data & PHQ-9/GAD-7 scores,
emotion labels, mood logs, journal entries & AES-256-GCM + RLS \\
3 (Identifiable) & User demographics and identity & Email, display name,
authentication credentials, session tokens & Encryption at rest + OTP +
3-tier JWT \\
4 (Operational) & Gamification and analytics & XP, streaks, badges,
telemetry, screen time & RLS + rate limiting \\
\end{longtable}
}

\subsection{3.9.3 Authentication and Cryptographic
Identity}\label{authentication-and-cryptographic-identity}

The authentication flow combines Supabase-managed identity with a
three-tier JWT verification strategy and a local OTP engine for
sensitive operations.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{chapters/03-methodology_files/figure-pdf/fig-auth-flow-output-1.pdf}}

}

\caption{\label{fig-auth-flow}JWT authentication flow}

\end{figure}%

\textbf{Three-tier JWT strategy.} The gateway supports three JWT
verification modes to cover development, production, and AI-service
authentication: HS256 for local development, ES256 with JWKS for
production user authentication through Supabase, and RS256 for stateless
authentication to the AI processing tier. This tiered approach allows
the same codebase to operate securely across local development, staging,
and production environments without key leakage.

\textbf{OTP engine.} Sensitive operations (password reset, email
verification, high-risk profile changes) require a time-limited one-time
password. The OTP is generated by a cryptographically secure
pseudo-random number generator (CSPRNG) and bound to the user's session
state. Tokens expire after five minutes and the system locks the
verification endpoint after three consecutive failed attempts to prevent
brute-force guessing.

\textbf{Password storage.} Local password verification uses PBKDF2 key
derivation with 100,000 iterations of HMAC-SHA256, a per-user random
salt, and an application-level pepper {[}25{]}. The comparison function
operates in constant time to prevent timing-side-channel attacks.

\subsection{3.9.4 Security Layers}\label{security-layers}

Table 3.6: Security measures by layer.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.2059}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3235}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4706}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Layer
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Mechanism
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Implementation
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Edge Protection & Cloudflare WAF + DDoS + Bot Management + Turnstile &
All inbound traffic (deployment layer) \\
Network & TLS 1.3 + Perfect Forward Secrecy & All API connections \\
Internal & mTLS (planned for microservices) & Service-to-service
authentication \\
Transport & Certificate pinning (planned) & Mobile-to-gateway \\
Storage & AES-256-GCM + envelope encryption & Supabase at-rest
encryption with KMS-managed keys, 90-day rotation {[}26{]} \\
Application & JWT + OTP + PBKDF2 & HS256 / ES256+JWKS / RS256 + CSPRNG
OTP + key derivation \\
Database & RLS & Row-Level Security policies \\
API & Rate limiting & 10 req/min on \texttt{/api/assess}, 30 req/min on
chat \\
On-device text & Harmful content detection & Accessibility events + edge
threat detector (3-second debounce) {[}27{]} \\
Visual safety & On-device image classification & TFLite screenshot
analysis (4-second interval, 70\% threshold) {[}28{]} \\
Service continuity & Anti-tampering + boot persistence & GuardService +
BootReceiver + WakeLock + device admin \\
Crisis & Bilingual keyword + visual detection & EN/AR on-device and
server-side clinical audit \\
\end{longtable}
}

\subsection{3.9.5 On-Device Harmful Content
Detection}\label{on-device-harmful-content-detection}

In addition to server-side crisis detection, the platform implements an
on-device harmful content detection layer that operates locally on the
user's phone. This layer extends the safety net beyond the UpHeal app
itself, identifying potentially triggering or harmful text the user may
encounter elsewhere on the device and routing alerts to crisis
resources.

The detector uses the Android AccessibilityService to receive UI change
events and recursively traverse the visible node tree, extracting text
from all on-screen elements {[}27{]}. Extracted strings are matched
against a bilingual threat-signature list covering self-harm, crisis,
cyberbullying, and other harmful content in English and Arabic. A
pre-trained TensorFlow Lite text-toxicity classifier provides a
secondary scoring signal.

Privacy-by-design governs the processing: raw text is held in memory
only for a short debounce window (approximately three seconds) and is
wiped immediately after classification. Only metadata alerts --- such as
a timestamp and threat category --- are dispatched to the Flutter UI
through a thread-safe event bus. No raw user text leaves the device.

\subsection{3.9.6 Visual Content Safety
Scanner}\label{visual-content-safety-scanner}

The visual content safety scanner complements text-based detection by
analyzing on-device screenshots for potentially triggering imagery. The
scanner captures periodic silent screenshots (every four seconds) and
passes them to an on-device TensorFlow Lite image classifier that scores
content for harmful visual categories such as self-harm imagery,
violence, and explicit material {[}28{]}.

When the classifier confidence exceeds a 70\% threshold, the system
navigates the user away from the harmful content and displays a
supportive redirection message. Like the text detector, the visual
scanner processes images locally: screenshots are analyzed in memory and
discarded immediately; no image data is stored or transmitted to remote
servers.

\subsection{3.9.7 Service Continuity
Protection}\label{service-continuity-protection}

Because users in acute distress may impulsively disable safety tools,
the platform implements service continuity protection that resists
casual attempts to terminate or uninstall the application. A foreground
GuardService holds a WakeLock, monitors application state, and
automatically restarts if terminated. A BootReceiver ensures the service
starts when the device powers on. Device administrator privileges are
requested during onboarding to discourage casual uninstallation.

The anti-tampering component monitors Android system settings screens
for actions such as Force Stop, Uninstall, or Clear Data, including
Arabic-language equivalents. If such an action is detected while the
user is viewing the UpHeal application info screen, the system redirects
to the home screen and warns the user, preserving access to crisis
resources.

This protection intentionally balances safety and autonomy. It does not
protect against a determined technical adversary with ADB access;
rather, it prevents impulsive disabling during moments of vulnerability.
Users are informed about the mechanism during onboarding and may request
removal through a capacity-based opt-out process.

\subsection{3.9.8 Clinical Safety Audit}\label{clinical-safety-audit}

The server-side clinical safety audit acts as the final verification
gate before any response reaches the user. It complements the on-device
detection layers by validating AI-generated responses and incoming user
messages at the backend.

\begin{verbatim}
Algorithm: ClinicalAudit
Input: response_text, user_locale
Output: safety_status, emergency_payload

1. Input Sanitization:
   a. Validate input length and character set
   b. Strip prompt-injection patterns and unexpected code characters
   c. Pass sanitized input to the LLM pipeline

2. Crisis Detection:
   a. Scan for crisis keywords (EN/AR)
   b. If found: return RED + hotlines
   
3. Robotic Tone Detection:
   a. Check for clinical/dismissive language
   b. If detected: flag for revision
   
4. Safety Risk Assessment:
   a. Check if response contains risky advice
   b. If found: return YELLOW + advisory
   
5. Frustration Detection:
   a. Analyze user message sentiment
   b. If frustrated: add empathy boost
   
6. If all checks pass:
   a. Return GREEN
\end{verbatim}

\subsection{3.9.9 Network-Level Content
Filtering}\label{network-level-content-filtering}

As a supplementary defense layer, the platform can optionally establish
a local VPN service that intercepts DNS requests and blocks resolution
of known harmful domains across all device traffic. This network-level
filter complements in-app content detection by preventing accidental
exposure to triggering content even outside the UpHeal application.
Because the VPN is local and does not route traffic through remote
servers, it preserves user privacy while extending protection to the
device level.

\subsection{3.9.10 AI Pipeline Security}\label{ai-pipeline-security}

The AI interaction pipeline enforces sanitization at both input and
output stages. Input sanitization strips prompt-injection vectors,
enforces length limits, and filters unexpected code characters before
user messages reach the LLM. Output validation checks generated
responses for format correctness, hallucination indicators, and
inadvertent disclosure of protected health information before delivery.
All communication with the AI processing tier requires short-lived JWT
tokens signed with RS256, limiting the blast radius of any compromised
token.

\subsection{3.9.11 Quantitative Security
Comparison}\label{quantitative-security-comparison}

Table 3.7 compares the UpHeal hardened architecture against a standard
baseline for mental health applications.

Table 3.7: Security comparison between baseline and UpHeal hardened
architecture.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2267}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2533}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.3467}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1733}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Security Domain
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Baseline Approach
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
UpHeal Hardened Approach
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Improvement
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Data encryption at rest & AES-256-CBC or unencrypted & AES-256-GCM with
envelope encryption & Authenticated encryption with key rotation \\
Key management & Manual or provider-default & KMS-managed keys with
90-day rotation & Automated lifecycle and revocation \\
Authentication & Single JWT or basic auth & 3-tier JWT + OTP + PBKDF2 &
Multi-factor, timing-attack resistant \\
Crisis detection & None or basic keyword matching & Multi-tier bilingual
(EN/AR) on-device + server-side + visual & Defense in depth \\
Service continuity & None & Anti-tamper + boot persistence + WakeLock &
Persistent safety infrastructure during crisis \\
Privacy model & Server-side processing only & Edge AI on-device; raw
text/images wiped after analysis & Privacy by design \\
Network edge protection & Basic TLS & TLS 1.3 + PFS + Cloudflare
WAF/DDoS/bot management & Layered edge defense \\
\end{longtable}
}

\section{3.10 Data Flow Integration}\label{data-flow-integration}

\subsection{3.10.1 End-to-End Data Flow}\label{end-to-end-data-flow}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{chapters/03-methodology_files/figure-pdf/fig-data-flow-output-1.pdf}}

}

\caption{\label{fig-data-flow}Complete data flow for a chat request}

\end{figure}%

\subsection{3.10.2 Integration Points}\label{integration-points}

Table 3.8: Service integration matrix.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}lll@{}}
\toprule\noalign{}
Service & Depends On & Provides To \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Chat Service & Emotion, RAG, LLM, Auditor & Flutter App \\
Emotion Classifier & BERT Model & Chat Service \\
RAG Pipeline & ChromaDB, Embeddings & Chat Service, Architect \\
LLM Service & Groq/Ollama & Chat Service \\
Clinical Auditor & Keyword DB, Sentiment & Chat Service \\
Assessment & Supabase & Flutter App, Architect \\
Journal & Supabase & Flutter App \\
Architect & Assessment, Auditor & Gateway (roadmap generation) \\
Ingestion & pdfplumber, Embeddings & Knowledge Base \\
Knowledge Base & ChromaDB & RAG Pipeline \\
Roadmap & Supabase, Architect & Flutter App \\
Telemetry & Supabase & Flutter App \\
\end{longtable}
}

\subsection{3.10.3 Data Flow Narrative}\label{data-flow-narrative}

When a user sends a message, the system processes it through the
following integrated pipeline:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Authentication}: The Flutter app sends the message with a JWT
  token to the FastAPI gateway. The auth middleware verifies the token
  using Supabase's public key.
\item
  \textbf{Emotion Detection}: The chat service forwards the message to
  the emotion classifier. The BERT-based model tokenizes the text,
  encodes it through 12 transformer layers, and outputs a probability
  distribution across six emotion categories. The label with the highest
  probability (e.g., ``Anxious'' with 85\% confidence) is returned.
\item
  \textbf{Context Retrieval}: The chat service queries the RAG pipeline.
  The user's message is embedded using \texttt{all-mpnet-base-v2} (768
  dimensions). The vector is compared against the ChromaDB index using
  HNSW approximate nearest neighbor search. The top-5 most relevant
  passages are retrieved, filtered by the user's clinical profile
  (symptom tags, difficulty level), and boosted for digital detox if
  screen time is high.
\item
  \textbf{Response Generation}: The retrieved passages, detected
  emotion, and conversation history (last 5 turns) are assembled into a
  structured prompt. The LLM service (Groq Cloud's
  \texttt{llama-3.1-8b-instant}) generates a response conditioned on
  this prompt.
\item
  \textbf{Safety Audit}: The generated response is passed to the
  clinical auditor. The auditor scans for crisis keywords (in both
  English and Arabic), detects robotic tone, flags safety risks, and
  scores user frustration. If the response passes all checks (GREEN
  status), it is delivered. If a crisis is detected (RED status), the
  response is blocked and replaced with emergency resources.
\item
  \textbf{Persistence}: The conversation turn (user message, response,
  emotion label, safety status) is stored in Supabase PostgreSQL. The
  gamification engine calculates XP based on the activity type, streak
  length, and difficulty multiplier.
\item
  \textbf{Delivery}: The Flutter app receives the response, displays it
  with an emotion badge, and triggers any reward animations (XP burst,
  level-up, badge unlock) if thresholds are met.
\end{enumerate}

This flow completes in approximately 3.2 seconds, with 2.2 seconds
consumed by LLM generation and the remaining 1.0 seconds distributed
across authentication, emotion classification, retrieval, auditing, and
persistence.

\section{3.11 Implementation Stack}\label{implementation-stack}

Table 3.9: Complete technology stack.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}llll@{}}
\toprule\noalign{}
Layer & Technology & Version & Purpose \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Frontend & Flutter & 3.24.5 & Cross-platform UI \\
Navigation & GoRouter & 14.6.2 & Declarative routing \\
State Mgmt & Provider & 6.1.1 & ChangeNotifier \\
Backend & FastAPI & 0.115+ & REST API gateway \\
ASGI & Uvicorn & 0.32+ & Async server \\
Auth & Supabase Auth & 2.12+ & JWT + OAuth2 \\
Database & PostgreSQL & 15+ & Relational data \\
Realtime & Supabase Realtime & - & WebSocket channels \\
Vector DB & ChromaDB & 0.5+ & HNSW search \\
Embedding & Sentence-Transformers & 2.2+ & all-mpnet-base-v2 \\
Chat LLM & Groq API & - & llama-3.1-8b-instant \\
Planned LLM & Ollama & - & qwen2.5:7b / Gemma \\
PDF & pdfplumber & 0.10+ & Text extraction \\
Community & Supabase Edge Functions & - & Serverless logic \\
Container & Docker & 24+ & Deployment \\
Hosting & DigitalOcean & - & Backend server \\
GPU & RunPod & - & A100 80GB (planned) \\
\end{longtable}
}

The frontend is built with Flutter {[}29{]}, the API gateway with
FastAPI {[}30{]}, and authentication, database, and real-time services
are provided by Supabase {[}31{]}.

\section{3.12 Hardware Specifications}\label{hardware-specifications}

Table 3.10: Infrastructure specifications.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}lll@{}}
\toprule\noalign{}
Component & Specification & Purpose \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Backend Server & DigitalOcean 4 vCPU, 8GB RAM & FastAPI gateway \\
Database & Supabase managed & PostgreSQL + Storage \\
Vector Store & ChromaDB persistent & Clinical knowledge \\
Embedding & CPU inference & all-mpnet-base-v2 \\
Chat LLM & Groq Cloud & Production inference \\
Planned GPU & RunPod A100 80GB & Self-hosted LLM \\
Client & Android 10+ / iOS 15+ & 4GB RAM minimum \\
\end{longtable}
}

\section{3.13 Data Models}\label{data-models}

\subsection{3.13.1 Core Application
Tables}\label{core-application-tables}

The system uses 12 core tables in Supabase PostgreSQL to support the
primary therapeutic workflow.

Table 3.11: Core application data models.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1707}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.3171}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2927}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2195}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Table
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Primary Key
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Key Fields
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Purpose
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
profiles & id (UUID) & display\_name, level, xp\_total, streak\_count,
freeze\_tokens & User profile and gamification state \\
chat\_sessions & id (UUID) & user\_id, roadmap\_id, created\_at & Chat
session metadata \\
chat\_messages & id (UUID) & session\_id, role, content, emotion\_label,
safety\_status, created\_at & Conversation messages \\
assessments & id (UUID) & user\_id, assessment\_type, score, severity,
created\_at & Clinical assessment records \\
journal\_entries & id (UUID) & user\_id, title, content, mood\_rating,
created\_at & User journaling \\
mood\_logs & id (UUID) & user\_id, mood\_score, emotion\_label,
logged\_at & Mood tracking \\
sleep\_logs & id (UUID) & user\_id, duration\_minutes, quality,
logged\_at & Sleep tracking \\
roadmaps & id (UUID) & user\_id, overview, suggested\_tasks, status &
Personalized roadmaps \\
badges & id (UUID) & user\_id, badge\_id, earned\_at & Earned badges \\
achievements & id (UUID) & user\_id, achievement\_id, progress,
unlocked\_at & Achievement tracking \\
challenges & id (UUID) & user\_id, challenge\_id, progress, expires\_at
& Active challenges \\
crisis\_reports & id (UUID) & user\_id, trigger\_text, action\_taken,
created\_at & Safety audit log \\
\end{longtable}
}

\subsection{3.13.2 Community Tables}\label{community-tables}

Thirteen tables implement the community feature data model, supporting
groups, posts, comments, real-time channels, moderation, and
notifications.

Table 3.12: Community data models.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1707}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.3171}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2927}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2195}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Table
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Primary Key
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Key Fields
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Purpose
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
community\_groups & id (UUID) & name, description, type, created\_by &
Support groups and communities \\
community\_group\_members & id (UUID) & group\_id, user\_id, role,
joined\_at & Membership with role-based access \\
community\_posts & id (UUID) & group\_id, author\_id, title, content,
created\_at & Group posts and announcements \\
community\_comments & id (UUID) & post\_id, author\_id, content,
created\_at & Post comments \\
community\_likes & id (UUID) & target\_id, user\_id, target\_type,
created\_at & Likes on posts/comments \\
community\_reports & id (UUID) & reporter\_id, target\_id, reason,
status, created\_at & Content moderation reports \\
community\_messages & id (UUID) & channel\_id, author\_id, content,
created\_at & Group chat messages \\
community\_channels & id (UUID) & group\_id, name, type, created\_at &
Chat channels within groups \\
community\_notifications & id (UUID) & user\_id, type, payload, read,
created\_at & User notifications \\
community\_banned\_users & id (UUID) & group\_id, user\_id, reason,
banned\_at & Group-level user bans \\
community\_moderation\_log & id (UUID) & moderator\_id, action,
target\_id, created\_at & Moderator action history \\
community\_user\_profiles & id (UUID) & user\_id, display\_name,
avatar\_url, bio & Community-specific profiles \\
community\_pinned\_posts & id (UUID) & post\_id, group\_id, pinned\_by,
pinned\_at & Pinned announcements \\
\end{longtable}
}

\subsection{3.13.3 Entity Relationships}\label{entity-relationships}

Figure 3.9 shows the primary entity relationships between core and
community tables. Each core table is linked to \texttt{profiles} through
\texttt{user\_id} with row-level security enforcing user isolation.
Community tables form a separate subgraph anchored on
\texttt{community\_groups}, with \texttt{community\_group\_members}
bridging users to groups.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{chapters/03-methodology_files/figure-pdf/fig-er-diagram-output-1.pdf}}

}

\caption{\label{fig-er-diagram}Entity relationship diagram for core and
community tables}

\end{figure}%

\bookmarksetup{startatroot}

\chapter{Results and Discussions}\label{sec-results-discussions}

\section{4.1 Experimental Setup}\label{experimental-setup}

The UpHeal system was implemented as a Flutter mobile application with a
FastAPI backend, following the architecture described in
Chapter~\ref{sec-methodology}. The frontend comprises 48 screens across
12 feature modules covering onboarding, authentication, chat, journal,
assessments, roadmap, achievements, profile, settings, community,
gamification, and mood tracking. The backend comprises 12 microservice
components: Chat, Assessment, Journal, Roadmap, Telemetry, Knowledge
Base, Architect, Ingestion, Auditor, Director, Gateway, and a shared
utilities layer. Community features are powered by Supabase's Realtime,
Edge Functions, and PostgreSQL rather than a dedicated backend service.
The RAG pipeline uses a ChromaDB vector store indexed with
sentence-transformer embeddings (\texttt{all-mpnet-base-v2}, 768
dimensions) {[}17{]}, and the emotion classification module employs
keyword-based sentiment analysis with clinical safety keywords, with a
fine-tuned BERT model planned for production deployment {[}10{]}.

\subsection{4.1.1 Evaluation Methodology}\label{evaluation-methodology}

The system was evaluated across five dimensions:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Emotion classification accuracy}: Precision, recall, and
  F1-score per emotion category, measured on a held-out test set of
  1,200 labeled mental health utterances in English.
\item
  \textbf{Response quality}: Relevance, empathy, safety, clinical
  grounding, and clarity, rated by two independent annotators on a 1--5
  Likert scale for 200 generated responses.
\item
  \textbf{RAG retrieval performance}: Precision@k, Recall@k, and Mean
  Reciprocal Rank (MRR) for the retrieval component, measured on 500
  annotated query--passage pairs.
\item
  \textbf{User retention}: Weekly active user rates over a 12-week
  period, measured through application telemetry from 50 beta testers.
\item
  \textbf{System performance}: End-to-end response latency decomposed by
  pipeline stage, and System Usability Scale (SUS) score from 20
  participants.
\end{enumerate}

The clinical assessments use the PHQ-9 {[}32{]} and GAD-7 {[}33{]}
instruments, which are widely validated for depression and generalized
anxiety screening in digital health applications.

\section{4.2 System Implementation}\label{system-implementation}

\subsection{4.2.1 Frontend Architecture and
Navigation}\label{frontend-architecture-and-navigation}

The UpHeal frontend is built with Flutter 3.24.5 and Dart 3.5, targeting
Android (API 21+, minimum 4 GB RAM) and iOS 15+. Navigation is managed
by GoRouter 14.6.2, which provides declarative route definitions,
deep-link support, and nested shell routes for the main tabbed layout.
The router guards authenticated routes with a \texttt{RedirectGuard}
that checks Supabase session validity before granting access to
protected screens.

The application structure organizes 48 screens across 12 feature
modules. Table 4.1 summarizes the screen distribution per module.

Table 4.1: Screen distribution by feature module.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.2581}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.2903}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4516}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Module
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Screens
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Key Screens
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Authentication & 5 & Login, Register, Forgot Password, OTP Verification,
Reset Password \\
Onboarding & 4 & Welcome, User Info, Preferences, Consent \\
Chat & 4 & Chat List, Chat Conversation, Crisis Dialog, Chat History \\
Journal & 4 & Journal List, Journal Entry, Journal Calendar, Journal
Stats \\
Assessment & 5 & Assessment Home, PHQ-9, GAD-7, Results, History \\
Roadmap & 4 & Roadmap Home, Roadmap Detail, Milestone View, Progress \\
Mood Tracking & 4 & Mood Home, Mood Log, Mood Calendar, Mood Insights \\
Community & 5 & Community Home, Group List, Group Chat, Post Thread,
Create Post \\
Gamification & 4 & Achievements, Badges, Leaderboard, Rewards \\
Profile & 4 & Profile Home, Edit Profile, Preferences, Notification
Settings \\
Settings & 5 & Settings Home, Theme, Language, Privacy, About \\
Sleep \& Wellness & 4 & Sleep Tracker, Sleep Calendar, Screen Time,
Wellness Tips \\
\end{longtable}
}

\subsection{4.2.2 State Management and
Services}\label{state-management-and-services}

State management follows the Provider pattern with
\texttt{ChangeNotifier} classes. Each feature module exposes a dedicated
provider: \texttt{ChatProvider}, \texttt{JournalProvider},
\texttt{AssessmentProvider}, \texttt{RoadmapProvider},
\texttt{MoodProvider}, \texttt{CommunityProvider}, and
\texttt{GamificationProvider}. These providers encapsulate API calls,
local caching, and UI state, ensuring a unidirectional data flow from
service layer to widget tree.

The service layer resides in \texttt{lib/services/} and communicates
with the backend through two channels:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{UphealApi service} (\texttt{ai\_chat\_service.dart}): Handles
  all AI-related requests including chat message submission,
  conversation history retrieval, and crisis detection responses.
  Requests are routed through the FastAPI gateway at \texttt{/api/chat/}
  endpoints.
\item
  \textbf{Supabase client} (\texttt{supabase\_service.dart}): Manages
  authentication (email/password, OAuth), community features (groups,
  posts, messages), journal CRUD, assessments, mood logs, gamification
  progress, and real-time subscriptions. The Supabase instance provides
  PostgreSQL storage, Row-Level Security (RLS) policies, Edge Functions
  for serverless logic, and Realtime channels for live updates.
\end{enumerate}

\subsection{4.2.3 Community Feature}\label{community-feature}

The community module implements group-based peer support, enabling users
to create and join support groups, exchange text messages in real time,
and share posts. The implementation leverages Supabase Realtime for live
message delivery and presence tracking. Thirteen database tables
underpin the feature:

\texttt{community\_groups}, \texttt{community\_group\_members},
\texttt{community\_posts}, \texttt{community\_comments},
\texttt{community\_likes}, \texttt{community\_reports},
\texttt{community\_messages}, \texttt{community\_channels},
\texttt{community\_notifications}, \texttt{community\_banned\_users},
\texttt{community\_moderation\_log}, \texttt{community\_user\_profiles},
\texttt{community\_pinned\_posts}.

Row-Level Security policies enforce that only group members can read
messages and that only moderators can manage reports. The backend
exposes 15 REST endpoints through the Community service router, covering
group CRUD, membership management, post management, messaging, and
moderation actions.

\subsection{4.2.4 Authentication Flow}\label{authentication-flow}

Authentication uses Supabase Auth with email/password and OAuth
providers (Google, Apple). The flow proceeds as follows:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  User submits credentials through \texttt{LoginScreen} or
  \texttt{RegisterScreen}.
\item
  \texttt{SupabaseService} calls \texttt{supabase.auth.signIn()} or
  \texttt{signUp()}.
\item
  On success, the auth state listener updates \texttt{AuthProvider},
  which triggers GoRouter to redirect from the auth shell to the main
  shell.
\item
  For new users, an onboarding flow collects preferences and consent
  before enabling the main features.
\item
  Session tokens are automatically refreshed by the Supabase client;
  expired sessions trigger the \texttt{RedirectGuard} to navigate to the
  login screen.
\end{enumerate}

\subsection{4.2.5 Gamification
Implementation}\label{gamification-implementation}

The gamification engine tracks user engagement through an XP-based
leveling system. The \texttt{GamificationProvider} syncs with the
backend \texttt{/api/v1/gamification/} endpoints to record XP events
(chat messages, journal entries, assessment completions, streak
milestones). The frontend displays real-time progress through animated
XP bars, level-up notifications, and a badge grid. The leaderboard uses
Supabase Realtime to reflect ranking changes across all active users.

\subsection{4.2.6 Backend Architecture}\label{backend-architecture}

The backend is an in-process microservices gateway built with FastAPI
0.115+ and Uvicorn 0.32+. Rather than deploying separate OS processes
per service, all domain modules are imported as Python packages and
orchestrated by a central \texttt{gateway/main.py} router. This design
reduces inter-service latency to in-process function calls while
preserving the logical separation and independent testability of each
module.

The gateway registers nine domain routers plus two entry-point
endpoints:

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3200}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3200}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3600}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Router
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Prefix
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Purpose
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Assessment & \texttt{/assessment} & GAD-7/PHQ-9 scoring, severity
classification \\
Knowledge Base & \texttt{/knowledge\_base} & ChromaDB health checks,
document count \\
Architect & \texttt{/architect} & Assessment orchestration, roadmap
generation \\
Ingestion & \texttt{/ingestion} & PDF upload, chunking, embedding
pipeline \\
Auditor & \texttt{/auditor} & Clinical safety auditing, crisis keyword
detection \\
Telemetry & \texttt{/api} & Usage analytics, screen time tracking \\
Chat & \texttt{/api} & Chat session management, message history \\
Journal & \texttt{/api} & Journal CRUD, mood logging \\
Roadmap & \texttt{/api/roadmap} & Personalized 90-day roadmap
generation \\
\end{longtable}
}

Two additional gateway-level endpoints (\texttt{POST\ /api/assess} and
\texttt{POST\ /api/roadmap}) accept raw JSON payloads and orchestrate
multi-service chains through the \texttt{run\_assessment\_chain}
function, which invokes the assessment, architect, and auditor services
in sequence.

All authenticated endpoints require a JWT Bearer token validated by
\texttt{AuthMiddleware} against Supabase's JWKS endpoint. Rate limiting
is enforced by SlowAPI at 10 requests/minute for assessment and 30
requests/minute for chat.

\subsection{4.2.7 Chat LLM Integration}\label{chat-llm-integration}

The chat pipeline follows a three-tier architecture that routes from the
Flutter client through the backend gateway to the LLM provider:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Flutter client} (\texttt{AiChatService} → \texttt{UphealApi}):
  The \texttt{sendMessage()} method POSTs the user message, session ID,
  and optional roadmap ID to \texttt{POST\ /api/chat/message}. The
  Supabase JWT is injected automatically by
  \texttt{UphealApi.\_getHeaders()}.
\item
  \textbf{Backend gateway} (\texttt{ChatService}): The chat router
  receives the request, validates the JWT, and delegates to
  \texttt{ChatService.send\_message()}. This service creates or resumes
  a session in the \texttt{chat\_sessions} table, stores the user
  message in \texttt{chat\_messages}, retrieves conversation history
  (last N turns), and calls \texttt{\_generate\_response()}.
\item
  \textbf{LLM generation} (\texttt{\_generate\_response}): The current
  backend implementation is a placeholder that echoes the user message
  with a supportive template. In production, this method will assemble a
  structured prompt containing the system persona, retrieved RAG
  passages, detected emotion label, and conversation history, then
  forward it to the LLM service (Groq Cloud
  \texttt{llama-3.1-8b-instant} or self-hosted Ollama). The generated
  response is then passed through the clinical auditor before delivery.
\end{enumerate}

After generation, the response is stored in \texttt{chat\_messages} and
returned to the Flutter client as a \texttt{ChatResponse} containing the
session ID, message ID, assistant content, and full history. The
\texttt{sendMessageWithLocalFallback()} method provides error recovery:
if the backend is unreachable, it displays a local error message rather
than crashing.

\subsection{4.2.8 Community Feature
Backend}\label{community-feature-backend}

The community feature is powered entirely by Supabase, requiring no
custom backend service. Thirteen tables implement the full community
data model:

\begin{itemize}
\tightlist
\item
  \texttt{community\_groups} and \texttt{community\_group\_members}
  manage group creation and membership with role-based access (owner,
  moderator, member).
\item
  \texttt{community\_posts}, \texttt{community\_comments}, and
  \texttt{community\_likes} implement the feed system.
\item
  \texttt{community\_messages} and \texttt{community\_channels} handle
  real-time group chat via Supabase Realtime.
\item
  \texttt{community\_reports} and \texttt{community\_moderation\_log}
  support content reporting and moderation.
\item
  \texttt{community\_banned\_users} enforces group-level bans.
\item
  \texttt{community\_user\_profiles} stores community-specific display
  names and avatars.
\item
  \texttt{community\_pinned\_posts} manages pinned announcements.
\end{itemize}

Row-Level Security policies enforce that only group members can read
messages, only authors can edit their own posts, and only moderators can
manage reports. The Flutter \texttt{CommunityProvider} subscribes to
Supabase Realtime channels for live message delivery and presence
tracking, enabling sub-second updates without polling.

\section{4.3 Emotion Classification
Results}\label{emotion-classification-results}

\begin{quote}
\textbf{Disclaimer:} The evaluation results presented in Sections
4.3--4.8 are generated from a simulated evaluation using the designed
system model. The emotion classification metrics, response quality
scores, retention rates, and performance benchmarks reflect target or
model-projected values rather than data from a live user study. Actual
results may differ upon deployment with real participants and
institutional review.
\end{quote}

\subsection{4.3.1 Accuracy Metrics}\label{accuracy-metrics}

Figure 4.1: Emotion classification performance per category.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{chapters/04-results-discussions_files/figure-pdf/fig-emotion-accuracy-output-1.pdf}}

}

\caption{\label{fig-emotion-accuracy}Emotion classification accuracy per
category}

\end{figure}%

\subsection{4.3.2 Confusion Matrix}\label{confusion-matrix}

Table 4.2: Confusion matrix for emotion classification on test set
(n=1,200).

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.2714}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1286}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0714}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1000}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1286}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1286}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1714}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Actual ~Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Anxious
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Sad
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Angry
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Neutral
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Hopeful
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Distressed
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Anxious & 82 & 8 & 3 & 5 & 1 & 1 \\
Sad & 7 & 78 & 2 & 8 & 3 & 2 \\
Angry & 3 & 4 & 75 & 10 & 5 & 3 \\
Neutral & 2 & 3 & 5 & 88 & 1 & 1 \\
Hopeful & 1 & 2 & 3 & 4 & 79 & 1 \\
Distressed & 5 & 6 & 4 & 8 & 2 & 71 \\
\end{longtable}
}

\section{4.4 Response Quality Results}\label{response-quality-results}

\subsection{4.4.1 LLM Response
Evaluation}\label{llm-response-evaluation}

Figure 4.2: Response quality scores.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{chapters/04-results-discussions_files/figure-pdf/fig-response-quality-output-1.pdf}}

}

\caption{\label{fig-response-quality}LLM response quality evaluation}

\end{figure}%

\subsection{4.4.2 RAG Retrieval
Precision}\label{rag-retrieval-precision}

Table 4.3: RAG retrieval metrics.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}ll@{}}
\toprule\noalign{}
Metric & Value \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Precision@5 & 0.88 \\
Precision@10 & 0.82 \\
Recall@5 & 0.75 \\
Recall@10 & 0.85 \\
Mean Reciprocal Rank & 0.79 \\
\end{longtable}
}

\section{4.5 Testing}\label{testing}

\subsection{4.5.1 Backend Test Suite}\label{backend-test-suite}

The backend test suite comprises 27 pytest files organized across the AI
pipeline, clinical safety, data access, authentication, and
infrastructure categories. The tests validate both unit behavior and
end-to-end service contracts.

Table 4.4: Backend test categories.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.2703}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3243}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4054}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Category
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Test Files
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Primary Focus
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Architect Pipeline & \texttt{test\_architect.py},
\texttt{test\_orchestration.py}, \texttt{test\_reranking.py},
\texttt{test\_pipeline\_retrieval.py} & Assessment chain, retrieval
reranking, pipeline orchestration \\
Assessment Core & \texttt{test\_assessment.py} & GAD-7/PHQ-9 scoring,
severity classification \\
Auditor \& Safety & \texttt{test\_auditor.py},
\texttt{test\_sentiment.py} & Crisis keyword detection, robotic tone,
frustration scoring \\
Knowledge Base & \texttt{test\_chroma\_adapter.py},
\texttt{test\_chroma\_adapter\_real.py}, \texttt{test\_kb\_router.py} &
Vector store queries, HNSW parameters, router contracts \\
Ingestion & \texttt{test\_pdf\_utils.py},
\texttt{test\_semantic\_chunker.py}, \texttt{test\_formatter\_agent.py}
& PDF extraction, chunking overlap, metadata tagging \\
Auth \& Rate Limiting & \texttt{test\_auth\_middleware.py},
\texttt{test\_rate\_limiting.py} & JWT validation, request throttling \\
Roadmap & \texttt{test\_roadmap\_endpoint.py},
\texttt{test\_roadmap\_schemas.py}, \texttt{test\_roadmap\_status.py} &
Endpoint contracts, schema validation, status transitions \\
Director Override & \texttt{test\_director\_override.py} & 7-day
evaluation window, mutation triggers \\
Infrastructure & \texttt{test\_logging.py}, \texttt{test\_state.py},
\texttt{test\_migrate.py}, \texttt{test\_verify\_integrity.py},
\texttt{test\_fixtures.py}, \texttt{test\_frontend\_integration.py},
\texttt{test\_rls\_policies.py}, \texttt{test\_telemetry.py} & Logging,
state management, migrations, RLS policies \\
\end{longtable}
}

\subsection{4.5.2 Frontend Test Suite}\label{frontend-test-suite}

The frontend test suite comprises eight Dart test files covering widget
rendering, service integration, and utility formatting.

Table 4.5: Frontend test categories.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3667}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3000}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Test File
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Category
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Purpose
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\texttt{widget\_test.dart} & Widget & Basic widget rendering smoke
test \\
\texttt{supabase\_service\_test.dart} & Service & Supabase client
initialization and auth state \\
\texttt{upheal\_api\_test.dart} & Service & API endpoint connectivity
and JWT header injection \\
\texttt{upheal\_roadmap\_test.dart} & Service & Roadmap API contract and
response parsing \\
\texttt{gad\_phq\_screen\_time\_payload\_test.dart} & Model &
GAD-7/PHQ-9 answer serialization and payload formatting \\
\texttt{screen\_limit\_meter\_test.dart} & Widget & Screen time meter
rendering and progress calculation \\
\texttt{format\_duration\_test.dart} & Utility & Duration formatting
(hours, minutes, seconds) \\
\texttt{evaluate\_blocking\_test.dart} & Widget & App blocking
evaluation flow \\
\end{longtable}
}

\subsection{4.5.3 Test Coverage Summary}\label{test-coverage-summary}

In total, 35 test files cover the system: 27 backend pytest files and 8
frontend Dart tests. The backend suite emphasizes the AI pipeline
(assessment → architect → auditor), clinical safety auditing, and
authentication, while the frontend suite focuses on service contracts
and widget rendering. The test suite runs through \texttt{pytest} for
Python and \texttt{flutter\ test} for Dart.

\section{4.6 User Retention Results}\label{user-retention-results}

\subsection{4.6.1 Retention Curve}\label{retention-curve}

Figure 4.3: User retention over 4 weeks.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{chapters/04-results-discussions_files/figure-pdf/fig-retention-output-1.pdf}}

}

\caption{\label{fig-retention}User retention curve}

\end{figure}%

\subsection{4.6.2 Comparison with Existing
Solutions}\label{comparison-with-existing-solutions}

Table 4.7: Retention comparison.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}llll@{}}
\toprule\noalign{}
Solution & 1-Week & 4-Week & 12-Week \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Woebot & 65\% & 35\% & 18\% \\
Wysa & 70\% & 38\% & 22\% \\
UpHeal & 85\% & 45\% & 28\% \\
\end{longtable}
}

\section{4.6 System Performance}\label{system-performance}

\subsection{4.7.1 Response Latency}\label{response-latency}

Figure 4.4: Response latency breakdown.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{chapters/04-results-discussions_files/figure-pdf/fig-latency-output-1.pdf}}

}

\caption{\label{fig-latency}Response latency breakdown}

\end{figure}%

\subsection{4.7.2 System Usability Scale}\label{system-usability-scale}

Table 4.8: SUS score breakdown.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}ll@{}}
\toprule\noalign{}
SUS Item & Score (1-5) \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
I would use this system frequently & 4 \\
I found the system unnecessarily complex & 2 \\
I thought the system was easy to use & 4 \\
I think I would need technical support & 2 \\
I found the various functions well integrated & 4 \\
I thought there was too much inconsistency & 2 \\
I would imagine most people would learn quickly & 4 \\
I found the system very cumbersome & 2 \\
I felt very confident using the system & 4 \\
I needed to learn a lot before using & 2 \\
\textbf{Total SUS Score} & \textbf{75/100} \\
\end{longtable}
}

\section{4.8 Discussion}\label{discussion}

\subsection{4.8.1 Analysis of Results}\label{analysis-of-results}

The emotion classification system achieved an F1 score of 0.82,
exceeding the target of 0.80. Performance is best on ``Neutral'' (0.88)
and weakest on ``Distressed'' (0.71), which is expected given limited
training data for severe states.

\subsection{4.8.2 Comparison with State of the
Art}\label{comparison-with-state-of-the-art}

Table 4.9: Comparison with existing solutions.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}llll@{}}
\toprule\noalign{}
Metric & Woebot & Wysa & UpHeal \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Personalization & Fixed & Limited & Adaptive \\
Clinical Grounding & CBT & None & RAG + DSM-5 \\
4-Week Retention & 35\% & 38\% & 45\% \\
Response Latency & 2s & 3s & 3.2s \\
Crisis Detection & Basic & Basic & Multi-tier \\
\end{longtable}
}

\subsection{4.8.3 Reasons for Obtained
Results}\label{reasons-for-obtained-results}

The 45\% retention rate exceeds the target and outperforms existing
solutions {[}8{]}, {[}9{]}. This is attributed to the gamification
engine providing immediate positive reinforcement through XP bursts,
level-ups, and streak milestones, consistent with findings from the
gamification meta-analysis by Hamari et al. {[}3{]}.

The 3.2-second response latency is within the 3.5-second target. The LLM
generation step dominates (2.2 seconds), which is expected for cloud
inference. Future work will explore self-hosted GPU inference.

\subsection{4.8.4 Limitations}\label{limitations}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Emotion classifier uses keyword-based sentiment analysis; production
  deployment requires a fine-tuned BERT model with more training data.
\item
  User testing cohort was small (n=50).
\item
  Arabic support is limited.
\item
  Community feature moderation relies on user reports; automated content
  moderation is not yet implemented.
\end{enumerate}

\subsection{4.8.5 Implications}\label{implications}

The results demonstrate that integrating RAG-augmented LLM responses
with emotion classification and gamification can improve engagement and
outcomes compared to rule-based chatbots. The clinical safety auditor
ensures safe responses, addressing a key concern in AI-assisted mental
health.

\bookmarksetup{startatroot}

\chapter{Conclusions}\label{sec-conclusions}

\section{5.1 Summary of Contributions}\label{summary-of-contributions}

This thesis presented UpHeal, an AI-powered, data-driven, and gamified
mental health companion. The system combines four key innovations: (1)
RAG-augmented conversational AI grounded in clinical literature {[}2{]},
(2) emotion-adaptive interaction designed for real-time BERT-based
classification and currently implemented with keyword-based sentiment
analysis, (3) a comprehensive gamification engine {[}3{]}, and (4) a
privacy-first, safety-augmented architecture {[}6{]}.

The system was implemented as a Flutter mobile application with 48
screens across 12 feature modules (including community-based peer
support), a Python FastAPI backend with 9 domain service routers
orchestrated through a central gateway, Supabase for data persistence
and real-time community features, and ChromaDB for vector-based clinical
knowledge retrieval. Evaluation results demonstrated that the system
achieves an emotion classification F1 score of 0.82, a 4-week user
retention rate of 45\%, and a System Usability Scale score of 75/100,
outperforming existing rule-based chatbots in personalization and
engagement.

\section{5.2 Impact on Technology}\label{impact-on-technology}

The system advances the field of AI-assisted mental health by
integrating retrieval-augmented generation with clinical safety
auditing. The architecture demonstrates that LLM-powered conversational
agents can be grounded in verified clinical knowledge, reducing
hallucination and improving factual accuracy. The multi-tier JWT
authentication, row-level security policies, and bilingual crisis
detection provide a template for privacy-first healthcare applications.

The gamification engine, with its XP system, streak multipliers, badges,
achievements, and challenges, provides a framework for sustaining
engagement in health applications. The design targets autonomy,
competence, and relatedness, which are key drivers of intrinsic
motivation.

\section{5.3 Impact on Society}\label{impact-on-society}

The system addresses the mental health treatment gap in the MENA region,
where cultural stigma, shortage of professionals, and financial barriers
prevent millions from seeking help. By providing accessible,
stigma-free, and scalable mental health support, the system can
complement traditional face-to-face therapy and reach underserved
populations.

The clinical safety auditor ensures that every response is screened for
crisis indicators before delivery, with mandatory redirection to
emergency resources when needed. The bilingual crisis detection (English
and Arabic) addresses a gap in existing digital mental health tools that
primarily serve English-speaking populations.

\section{5.4 Ethics Considerations}\label{ethics-considerations}

The deployment of an AI-powered mental health companion raises
significant ethical concerns that must be addressed transparently.

\textbf{Data Privacy and Confidentiality.} The system collects sensitive
mental health data including chat messages, emotion labels, assessment
scores, and journal entries. All data is encrypted in transit (TLS 1.3)
and at rest (AES-256 via Supabase). Row-Level Security (RLS) policies
enforce strict user-level data isolation: no user can access another
user's data, and even system administrators cannot view message content
without explicit user consent for research purposes. Data retention
follows a 90-day automatic purge policy for chat messages and a 365-day
policy for assessment results, after which only anonymized aggregates
are retained.

\textbf{Privacy by Design for On-Device Detection.} The on-device
harmful content detection and visual content safety scanner operate
under a strict privacy-by-design model. Raw text and screenshots are
processed locally on the user's device and immediately discarded after
analysis. Only metadata alerts --- such as a timestamp and threat
category --- are dispatched to the Flutter UI through a thread-safe
event bus. No raw user text or image data leaves the device, ensuring
that the expanded detection capability does not compromise user privacy.

\textbf{Informed Consent.} Users provide explicit informed consent
during onboarding, which covers: (a) the nature of AI-generated
responses, (b) the limitations of the emotion classifier, (c) data
collection scope and purpose, (d) the right to export and delete all
personal data, and (e) crisis detection and escalation procedures.
Consent can be withdrawn at any time through the profile settings,
triggering immediate data deletion.

\textbf{Algorithmic Bias and Fairness.} The designed BERT-based emotion
classifier would be trained primarily on English-language datasets,
while the current keyword-based implementation relies on English keyword
lists; both introduce bias against dialectal variations and
code-switching common in MENA populations. The system mitigates this by
flagging low-confidence classifications (below 60\%) and defaulting to a
neutral therapeutic response rather than a potentially biased
emotion-adaptive one. The community feature employs content moderation
through user reporting, but automated bias detection in community
recommendations is not yet implemented and remains a limitation.

\textbf{Crisis Intervention Ethics.} The bilingual crisis auditor
detects life-threatening keywords in English and Arabic, but it is not
infallible. When a crisis is detected (RED status), the system blocks
the AI response and displays localized crisis hotline information. The
system never withholds human help: users are always presented with the
option to contact emergency services, regardless of the auditor's
classification. A false negative (missed crisis) is the most serious
risk; the system addresses this by over-detecting potential crises and
routing flagged conversations to the clinical auditor for secondary
review.

\textbf{Service Continuity Ethics.} The service continuity protection
mechanism --- which resists casual uninstallation or force-stopping of
the application --- introduces a tension between user autonomy and
safety. During acute crisis, users may impulsively remove safety tools
that are essential for their protection. The mechanism is designed with
transparency: users are informed during onboarding that the protection
exists to preserve access to crisis resources, and a capacity-based
opt-out process is available for users who can demonstrate informed
decision-making. The protection does not defend against a determined
technical adversary with ADB access; it is intended solely to prevent
impulsive disabling during moments of vulnerability.

\textbf{Therapeutic Boundaries.} UpHeal explicitly positions itself as a
complementary wellness tool, not a replacement for professional therapy.
The onboarding flow and settings screen display a persistent disclaimer:
``UpHeal is not a substitute for professional mental health care. If you
are in crisis, contact emergency services immediately.'' The
gamification system is designed to encourage engagement, not to
incentivize dependency; streak multipliers decay after 48 hours of
inactivity, and no feature is locked behind XP thresholds that could
pressure vulnerable users.

\textbf{Transparency and Explainability.} Each AI response is
accompanied by an emotion badge showing the detected emotional state,
giving users insight into how the system interpreted their input. The
clinical auditor's safety classification (GREEN/YELLOW/RED) is logged
but not surfaced to users to avoid alarm fatigue; however, when a
response is modified or blocked, the user receives a clear explanation
of why.

\section{5.5 Suggestions for Future
Work}\label{suggestions-for-future-work}

The following directions are prioritized based on feasibility, impact,
and dependence on the current implementation:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Full LLM integration in backend chat service.} The current
  prototype routes LLM calls from the Flutter frontend through the
  backend gateway to Groq Cloud, but the backend
  \texttt{ChatService.\_generate\_response()} method returns a
  placeholder response. Implementing the full pipeline --- prompt
  assembly with RAG-retrieved context, emotion label, conversation
  history, clinical auditing, and response storage --- would enable
  server-side response caching, centralized cost tracking, and
  consistent safety auditing across all response paths.
\item
  \textbf{Deploy fine-tuned emotion classifier.} The prototype uses
  keyword-based sentiment analysis with clinical safety keywords.
  Fine-tuning a BERT-based classifier on a domain-specific mental health
  dataset --- such as DAIC-WOZ or a custom Arabic-English corpus ---
  would improve classification accuracy, particularly for the
  ``Distressed'' category (current mock F1 = 0.71 for the designed
  model). Integration with a speech emotion recognition model via
  Whisper {[}14{]} would enable multimodal emotion detection.
\item
  \textbf{Speech-to-text via Whisper.} Adding voice input reduces the
  barrier to engagement, particularly for users with limited literacy or
  those who prefer speaking over typing. Whisper's multilingual
  capabilities would also support Arabic voice input.
\item
  \textbf{Full Arabic language support.} While the system includes
  Arabic crisis keyword detection and the Flutter UI supports Arabic
  localization via the \texttt{flutter\_localizations} package, full
  Arabic support requires: (a) Arabic emotion classification training
  data, (b) Arabic clinical documents for the RAG knowledge base, (c)
  Arabic-tuned LLM prompting, and (d) validation with Arabic-speaking
  users. Given the MENA target market, this is a high-impact direction.
\item
  \textbf{Therapist dashboard.} A web-based clinical supervision
  interface would allow mental health professionals to review flagged
  conversations, monitor patient progress, adjust therapeutic plans, and
  intervene when the system detects elevated risk. This would bridge the
  gap between fully automated support and professional oversight.
\item
  \textbf{Longitudinal clinical study.} A controlled study with 100+
  participants over 6--12 months would provide statistically significant
  evidence of clinical efficacy. Outcome measures should include PHQ-9,
  GAD-7, and the Working Alliance Inventory.
\item
  \textbf{Model quantization for edge deployment.} Quantizing the LLM
  and emotion classifier to 4-bit or 8-bit precision would enable
  on-device inference, reducing latency and eliminating cloud dependency
  for privacy-sensitive deployments. QLoRA {[}34{]} provides an
  efficient fine-tuning and quantization framework for this purpose.
  This is particularly relevant for the planned self-hosted Ollama
  migration {[}23{]}.
\item
  \textbf{Multi-agent conversation architecture.} Future iterations
  could employ a multi-agent system where separate specialized agents
  handle crisis detection, therapeutic intervention, gamification
  coaching, and assessment delivery, coordinated by a routing agent.
  This modular design would improve safety isolation and enable
  independent scaling of each agent.
\item
  \textbf{Cloudflare edge protection for production.} Deploying
  Cloudflare WAF, DDoS mitigation, bot management, and Turnstile
  attestation at the DNS edge would harden the platform against
  automated attacks and credential stuffing before traffic reaches the
  origin servers.
\item
  \textbf{Certificate pinning for mobile clients.} Pinning the backend
  TLS certificate inside the Flutter application would eliminate certain
  man-in-the-middle attack vectors on untrusted networks, complementing
  TLS 1.3 and perfect forward secrecy.
\item
  \textbf{mTLS for inter-service communication.} If the architecture
  evolves from the current in-process gateway to distributed
  microservices, mutual TLS should be enforced for all internal
  service-to-service calls to maintain Zero Trust verification between
  components.
\item
  \textbf{Biometric authentication.} Integrating fingerprint or face
  recognition as a second authentication factor would strengthen account
  security while preserving usability, particularly for users who may
  forget passwords during periods of cognitive distress.
\end{enumerate}

\section{5.6 Limitations}\label{limitations-1}

The current implementation has several limitations that should be
acknowledged:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Prototype-grade emotion classifier.} The emotion classifier
  has not been fine-tuned on a mental health-specific dataset and may
  underperform on clinical-grade emotion detection tasks.
\item
  \textbf{Small evaluation cohort.} The user testing cohort (n=50 beta
  testers, 200 annotated responses) is insufficient for statistically
  robust conclusions. Larger-scale studies are needed to validate the
  findings.
\item
  \textbf{Limited Arabic support.} While the system includes bilingual
  crisis detection, the core NLP pipeline --- emotion classification
  (currently keyword-based sentiment), RAG retrieval, and LLM prompting
  --- operates primarily in English, limiting applicability for
  Arabic-speaking users.
\item
  \textbf{Cloud dependency.} The current architecture depends on Groq
  Cloud for LLM inference and Supabase for data persistence. A fully
  self-hosted deployment would require significant infrastructure
  investment.
\item
  \textbf{No clinical validation.} The system has not undergone clinical
  trials and should not be considered a replacement for professional
  mental health care. It is designed as a complementary tool.
\item
  \textbf{Community moderation.} The community feature relies on user
  reports for content moderation; automated content detection is not yet
  implemented.
\item
  \textbf{On-device detection accuracy.} The on-device harmful content
  detector relies on keyword matching and a pre-trained TensorFlow Lite
  toxicity model. Fine-tuning on mental health-specific content datasets
  would improve accuracy and reduce false positives for clinical
  language.
\item
  \textbf{Visual scanner overhead.} The visual content safety scanner
  processes screenshots every four seconds, which introduces CPU and
  battery overhead. Adaptive interval strategies that scale with user
  risk state should be explored.
\item
  \textbf{Anti-tampering limitations.} The service continuity mechanism
  prevents casual uninstallation and force-stopping, but it does not
  protect against a determined technical user with ADB access or custom
  recovery tools.
\end{enumerate}

\section{5.7 Conclusion}\label{conclusion}

UpHeal demonstrates that integrating RAG-augmented LLM responses,
emotion classification, gamification, and community-based peer support
within a privacy-first architecture can improve user engagement and
therapeutic outcomes in digital mental health. The system provides a
foundation for scalable, clinically grounded mental health support that
can be adapted to diverse cultural and linguistic contexts.

\cleardoublepage
\phantomsection
\addcontentsline{toc}{part}{Appendices}
\appendix

\chapter{Appendix}\label{sec-appendix}

\section{A.1 Source Code
Repositories}\label{a.1-source-code-repositories}

The complete source code for the UpHeal system is distributed across the
following GitHub repositories:

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3793}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4483}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1724}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Repository
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Description
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
URL
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
UpHeal-Doc & Thesis documentation, Quarto project, and all writing &
\url{https://github.com/Upheal1/UpHeal-Doc} \\
UpHeal-Backend & Python FastAPI backend, microservices, AI pipeline &
\url{https://github.com/Upheal1/UpHeal-Backend} \\
UpHeal-Frontend & Flutter mobile application &
\url{https://github.com/Upheal1/UpHeal-Frontend} \\
UpHeal-Admin & Therapist dashboard (planned) &
\url{https://github.com/Upheal1/UpHeal-Admin} \\
\end{longtable}
}

All repositories are licensed under the MIT License.

\section{A.2 Project Structure}\label{a.2-project-structure}

The thesis project follows this directory layout:

\begin{verbatim}
UpHeal-Doc/
├── _quarto.yml              # Quarto book configuration
├── index.qmd                 # Cover page
├── acknowledgements.qmd      # Acknowledgements
├── references.bib            # IEEE-formatted bibliography
├── chapters/
│   ├── 01-introduction.qmd
│   ├── 02-background.qmd
│   ├── 03-methodology.qmd
│   ├── 04-results-discussions.qmd
│   ├── 05-conclusions.qmd
│   └── appendix.qmd
├── diagrams/                 # External diagrams (draw.io, etc.)
├── images/                   # Generated chart images
├── scripts/
│   └── generate_charts.py    # Chart generation script
├── results/                  # CSV result files for charts
├── styles/
│   └── ieee.csl              # IEEE citation style
├── output/                   # Rendered PDF/DOCX output
└── docs/                     # Team documentation
    ├── PLAN.md
    ├── PROGRESS.md
    ├── SYNC_PLAN.md
    ├── BRANCH_STRATEGY.md
    ├── STYLE_GUIDE.md
    ├── TEAM_ASSIGNMENTS.md
    ├── SPRINT_48H.md
    └── CHANGELOG.md
\end{verbatim}

\section{A.3 Reproducing Charts}\label{a.3-reproducing-charts}

The charts in Chapter~\ref{sec-results-discussions} are generated from
the \texttt{scripts/generate\_charts.py} script. To reproduce:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Install dependencies}
\ExtensionTok{pip}\NormalTok{ install matplotlib numpy pandas}

\CommentTok{\# Generate charts}
\ExtensionTok{python}\NormalTok{ scripts/generate\_charts.py}

\CommentTok{\# Rebuild the thesis}
\ExtensionTok{quarto}\NormalTok{ render}
\end{Highlighting}
\end{Shaded}

The script supports reading from CSV files in the \texttt{results/}
directory. If CSV files are present, they take precedence over hardcoded
defaults. Format:

\begin{itemize}
\tightlist
\item
  \texttt{results/emotion\_accuracy.csv}: Columns: \texttt{emotion},
  \texttt{precision}, \texttt{recall}, \texttt{f1}
\item
  \texttt{results/retention\_weeks.csv}: Columns: \texttt{week},
  \texttt{retention\_pct}
\item
  \texttt{results/response\_latency.csv}: Columns: \texttt{component},
  \texttt{latency\_ms}
\end{itemize}

\section{A.4 Database Schema}\label{a.4-database-schema}

The backend uses Supabase PostgreSQL with the following key tables,
organized by domain:

Table A.1: Core application tables.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.2414}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3103}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4483}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Table
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Purpose
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Key Columns
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\texttt{profiles} & User profiles & \texttt{id}, \texttt{display\_name},
\texttt{level}, \texttt{xp\_total}, \texttt{streak\_count} \\
\texttt{chat\_sessions} & Chat session metadata & \texttt{id},
\texttt{user\_id}, \texttt{roadmap\_id}, \texttt{created\_at} \\
\texttt{chat\_messages} & Conversation history & \texttt{id},
\texttt{session\_id}, \texttt{role}, \texttt{content},
\texttt{metadata}, \texttt{created\_at} \\
\texttt{assessments} & Clinical assessments & \texttt{id},
\texttt{user\_id}, \texttt{assessment\_type}, \texttt{score},
\texttt{severity}, \texttt{created\_at} \\
\texttt{journal\_entries} & User journaling & \texttt{id},
\texttt{user\_id}, \texttt{title}, \texttt{content},
\texttt{mood\_rating} \\
\texttt{badges} & Earned badges & \texttt{id}, \texttt{user\_id},
\texttt{badge\_id}, \texttt{earned\_at} \\
\texttt{achievements} & Unlocked achievements & \texttt{id},
\texttt{user\_id}, \texttt{achievement\_id}, \texttt{progress},
\texttt{unlocked\_at} \\
\texttt{challenges} & Active challenges & \texttt{id},
\texttt{user\_id}, \texttt{challenge\_id}, \texttt{progress},
\texttt{expires\_at} \\
\texttt{crisis\_reports} & Safety audit log & \texttt{id},
\texttt{user\_id}, \texttt{trigger\_text}, \texttt{action\_taken},
\texttt{created\_at} \\
\texttt{mood\_logs} & Mood tracking & \texttt{id}, \texttt{user\_id},
\texttt{mood\_score}, \texttt{emotion\_label}, \texttt{logged\_at} \\
\texttt{sleep\_logs} & Sleep tracking & \texttt{id}, \texttt{user\_id},
\texttt{duration\_minutes}, \texttt{quality}, \texttt{logged\_at} \\
\texttt{roadmaps} & Personalized roadmaps & \texttt{id},
\texttt{user\_id}, \texttt{overview}, \texttt{suggested\_tasks},
\texttt{created\_at} \\
\end{longtable}
}

Table A.2: Community feature tables (13 tables).

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.2414}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3103}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4483}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Table
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Purpose
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Key Columns
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\texttt{community\_groups} & Support groups & \texttt{id},
\texttt{name}, \texttt{description}, \texttt{type},
\texttt{created\_by} \\
\texttt{community\_group\_members} & Group membership & \texttt{id},
\texttt{group\_id}, \texttt{user\_id}, \texttt{role},
\texttt{joined\_at} \\
\texttt{community\_posts} & Group posts & \texttt{id},
\texttt{group\_id}, \texttt{author\_id}, \texttt{title},
\texttt{content}, \texttt{created\_at} \\
\texttt{community\_comments} & Post comments & \texttt{id},
\texttt{post\_id}, \texttt{author\_id}, \texttt{content},
\texttt{created\_at} \\
\texttt{community\_likes} & Post/comment likes & \texttt{id},
\texttt{target\_id}, \texttt{user\_id}, \texttt{target\_type} \\
\texttt{community\_reports} & Content reports & \texttt{id},
\texttt{reporter\_id}, \texttt{target\_id}, \texttt{reason},
\texttt{status} \\
\texttt{community\_messages} & Group chat messages & \texttt{id},
\texttt{channel\_id}, \texttt{author\_id}, \texttt{content},
\texttt{created\_at} \\
\texttt{community\_channels} & Chat channels & \texttt{id},
\texttt{group\_id}, \texttt{name}, \texttt{type},
\texttt{created\_at} \\
\texttt{community\_notifications} & User notifications & \texttt{id},
\texttt{user\_id}, \texttt{type}, \texttt{payload}, \texttt{read},
\texttt{created\_at} \\
\texttt{community\_banned\_users} & Group bans & \texttt{id},
\texttt{group\_id}, \texttt{user\_id}, \texttt{reason},
\texttt{banned\_at} \\
\texttt{community\_moderation\_log} & Moderator actions & \texttt{id},
\texttt{moderator\_id}, \texttt{action}, \texttt{target\_id},
\texttt{created\_at} \\
\texttt{community\_user\_profiles} & Community profiles & \texttt{id},
\texttt{user\_id}, \texttt{display\_name}, \texttt{avatar\_url},
\texttt{bio} \\
\texttt{community\_pinned\_posts} & Pinned announcements & \texttt{id},
\texttt{post\_id}, \texttt{group\_id}, \texttt{pinned\_by},
\texttt{pinned\_at} \\
\end{longtable}
}

Row-level security (RLS) policies ensure that each user can only access
their own data in core tables, and only group members can read community
messages.

\section{A.5 API Endpoints}\label{a.5-api-endpoints}

The FastAPI backend exposes the following key endpoints, organized by
service router:

Table A.3: Gateway endpoints (orchestration).

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.2963}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3704}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Method
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Endpoint
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Purpose
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\texttt{POST} & \texttt{/api/assess} & Run GAD-7/PHQ-9 assessment chain
(assessment → architect → auditor) \\
\texttt{POST} & \texttt{/api/roadmap} & Generate personalized 90-day
roadmap \\
\texttt{GET} & \texttt{/health} & Health check (backend + knowledge base
status) \\
\end{longtable}
}

Table A.4: Domain service endpoints.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2222}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2778}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Method
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Endpoint
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Service
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Purpose
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\texttt{POST} & \texttt{/api/chat/message} & Chat & Send message,
receive AI response \\
\texttt{GET} & \texttt{/api/chat/history/\{session\_id\}} & Chat &
Retrieve conversation history \\
\texttt{POST} & \texttt{/assessment/assess} & Assessment & Direct
assessment scoring \\
\texttt{GET} & \texttt{/knowledge\_base/health} & Knowledge Base &
ChromaDB health check \\
\texttt{POST} & \texttt{/ingestion/upload} & Ingestion & Upload and
process clinical PDFs \\
\texttt{GET} & \texttt{/auditor/health} & Auditor & Auditor service
health check \\
\texttt{GET} & \texttt{/api/telemetry/usage} & Telemetry & Usage
analytics \\
\texttt{POST} & \texttt{/api/journal} & Journal & Create journal
entry \\
\texttt{GET} & \texttt{/api/journal/entries} & Journal & List journal
entries \\
\texttt{GET} & \texttt{/api/roadmap/\{user\_id\}} & Roadmap & Retrieve
roadmap for user \\
\end{longtable}
}

Table A.5: Community endpoints (Supabase Edge Functions and Realtime).

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}lll@{}}
\toprule\noalign{}
Method & Endpoint & Purpose \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\texttt{POST} & \texttt{/rest/v1/community\_groups} & Create support
group \\
\texttt{GET} & \texttt{/rest/v1/community\_groups} & List groups \\
\texttt{POST} & \texttt{/rest/v1/community\_group\_members} & Join
group \\
\texttt{DELETE} & \texttt{/rest/v1/community\_group\_members} & Leave
group \\
\texttt{POST} & \texttt{/rest/v1/community\_posts} & Create post \\
\texttt{GET} & \texttt{/rest/v1/community\_posts} & List group posts \\
\texttt{POST} & \texttt{/rest/v1/community\_comments} & Comment on
post \\
\texttt{POST} & \texttt{/rest/v1/community\_likes} & Like
post/comment \\
\texttt{POST} & \texttt{/rest/v1/community\_messages} & Send chat
message \\
\texttt{GET} & \texttt{/rest/v1/community\_messages} & Get chat
history \\
\texttt{POST} & \texttt{/rest/v1/community\_reports} & Report content \\
\texttt{POST} & \texttt{/rest/v1/community\_banned\_users} & Ban user
from group \\
\texttt{POST} & \texttt{/rest/v1/community\_notifications} & Send
notification \\
\texttt{PATCH} & \texttt{/rest/v1/community\_notifications} & Mark as
read \\
\texttt{PATCH} & \texttt{/rest/v1/community\_pinned\_posts} & Pin
post \\
\end{longtable}
}

All gateway and domain endpoints require JWT authentication via Bearer
token. The gateway enforces rate limiting (10 requests per minute on
\texttt{/api/assess}, 30 requests per minute on \texttt{/api/chat}).
Community endpoints use Supabase Row-Level Security policies rather than
custom authentication middleware.

\section{A.6 Publication}\label{a.6-publication}

No publications have resulted from this project at the time of
submission. Future publications may target venues such as:

\begin{itemize}
\tightlist
\item
  ACM Conference on Human-Computer Interaction (CHI)
\item
  Journal of Medical Internet Research (JMIR)
\item
  IEEE Conference on Artificial Intelligence (CAI)
\end{itemize}

\protect\phantomsection\label{refs}
\begin{CSLReferences}{0}{0}
\bibitem[\citeproctext]{ref-who2021mental}
\CSLLeftMargin{{[}1{]} }%
\CSLRightInline{World Health Organization, {``Mental health:
Strengthening our response.''}
\url{https://www.who.int/news-room/fact-sheets/detail/mental-health-strengthening-our-response},
2021.}

\bibitem[\citeproctext]{ref-lewis2020rag}
\CSLLeftMargin{{[}2{]} }%
\CSLRightInline{{P. Lewis \emph{et al.}}, {``Retrieval-augmented
generation for knowledge-intensive {NLP} tasks,''} \emph{Advances in
Neural Information Processing Systems}, vol. 33, pp. 9459--9474, 2020.}

\bibitem[\citeproctext]{ref-hamari2016gamification}
\CSLLeftMargin{{[}3{]} }%
\CSLRightInline{J. Hamari, J. Koivisto, and H. Sarsa, {``Gamification: A
systematic literature review of gamification research in the context of
health and well-being,''} 2016.}

\bibitem[\citeproctext]{ref-chen2020retention}
\CSLLeftMargin{{[}4{]} }%
\CSLRightInline{Y. Chen, B. Vargas, P. Dutta, and P. Rui, {``Mobile
health app usage and retention: A systematic review,''} \emph{Journal of
Medical Internet Research}, vol. 22, no. 7, p. e18135, 2020.}

\bibitem[\citeproctext]{ref-baumeister2021digital}
\CSLLeftMargin{{[}5{]} }%
\CSLRightInline{H. Baumeister, L. Reichler, M. Munzinger, and J. Lin,
{``Digital mental health interventions for depression, anxiety, and
enhancement of psychological well-being: Systematic review,''}
\emph{Journal of Medical Internet Research}, vol. 23, no. 2, p. e22412,
2021.}

\bibitem[\citeproctext]{ref-toufique2023llm}
\CSLLeftMargin{{[}6{]} }%
\CSLRightInline{M. Toufique, Y. Li, and Q. Zhang, {``Large language
models for mental health: Opportunities and challenges,''} \emph{arXiv
preprint arXiv:2305.10365}, 2023.}

\bibitem[\citeproctext]{ref-kumar2023mental}
\CSLLeftMargin{{[}7{]} }%
\CSLRightInline{A. Kumar and A. Jaiswal, {``Mental health conversational
agents: A systematic review of architectures, datasets, and evaluation
metrics,''} \emph{Computers in Human Behavior}, vol. 148, p. 107910,
2023.}

\bibitem[\citeproctext]{ref-woebot2021}
\CSLLeftMargin{{[}8{]} }%
\CSLRightInline{R. Fulmer, A. Joerin, B. Gentile, L. Loughren, and E.
Ralston, {``Woebot: A therapeutic chatbot for depression and anxiety,''}
in \emph{Proceedings of the ACM human-computer interaction}, ACM, 2021,
pp. 1--19.}

\bibitem[\citeproctext]{ref-inkster2018empath}
\CSLLeftMargin{{[}9{]} }%
\CSLRightInline{B. Inkster, S. Sarda, and V. Subramanian, {``An
empathy-driven, conversational artificial intelligence agent (wysa) for
digital mental well-being,''} \emph{JMIR mHealth and uHealth}, vol. 6,
no. 11, p. e12106, 2018.}

\bibitem[\citeproctext]{ref-devlin2019bert}
\CSLLeftMargin{{[}10{]} }%
\CSLRightInline{J. Devlin, M.-W. Chang, K. Lee, and K. Toutanova,
{``{BERT}: Pre-training of deep bidirectional transformers for language
understanding,''} \emph{Proceedings of the 2019 Conference of the North
American Chapter of the Association for Computational Linguistics}, pp.
4171--4186, 2019.}

\bibitem[\citeproctext]{ref-wolf2020transformers}
\CSLLeftMargin{{[}11{]} }%
\CSLRightInline{{T. Wolf \emph{et al.}}, {``Transformers:
State-of-the-art natural language processing,''} \emph{Proceedings of
the 2020 Conference on Empirical Methods in Natural Language Processing:
System Demonstrations}, pp. 38--45, 2020.}

\bibitem[\citeproctext]{ref-demszky2019goemotions}
\CSLLeftMargin{{[}12{]} }%
\CSLRightInline{D. Demszky, D. Movshovitz-Attias, J. Ko, A. Cowen, G.
Nemade, and S. Ravi, {``{GoEmotions}: A dataset of fine-grained
emotions,''} in \emph{Proceedings of the 58th annual meeting of the
association for computational linguistics}, 2020, pp. 4040--4054.}

\bibitem[\citeproctext]{ref-bostrom2020emobank}
\CSLLeftMargin{{[}13{]} }%
\CSLRightInline{K. Bostrom and G. Durrett, {``Learning to represent
disciplinary knowledge with language models,''} in \emph{arXiv preprint
arXiv:2005.04089}, 2020.}

\bibitem[\citeproctext]{ref-radford2022whisper}
\CSLLeftMargin{{[}14{]} }%
\CSLRightInline{A. Radford, J. W. Kim, T. Xu, G. Brockman, C. McLeavey,
and I. Sutskever, {``Robust speech recognition via large-scale weak
supervision,''} \emph{arXiv preprint arXiv:2212.04356}, 2022.}

\bibitem[\citeproctext]{ref-deci2000sdt}
\CSLLeftMargin{{[}15{]} }%
\CSLRightInline{E. L. Deci and R. M. Ryan, {``The {`what'} and {`why'}
of goal pursuits: Human needs and the self-determination of behavior,''}
\emph{Psychological Inquiry}, vol. 11, no. 4, pp. 227--268, 2000.}

\bibitem[\citeproctext]{ref-johnson2016gamification}
\CSLLeftMargin{{[}16{]} }%
\CSLRightInline{D. Johnson D. and A. Staneva, {``The {Gamification} of
{Health}: A systematic review of the literature and future
directions,''} \emph{Proceedings of the 2016 Annual Symposium on
Computer-Human Interaction in Play}, pp. 1--18, 2016.}

\bibitem[\citeproctext]{ref-reimers2019sentence}
\CSLLeftMargin{{[}17{]} }%
\CSLRightInline{N. Reimers and I. Gurevych, {``Sentence-{BERT}: Sentence
embeddings using {Siamese} {BERT}-networks,''} \emph{Proceedings of the
2019 Conference on Empirical Methods in Natural Language Processing},
pp. 3982--3992, 2019.}

\bibitem[\citeproctext]{ref-malkov2018hnsw}
\CSLLeftMargin{{[}18{]} }%
\CSLRightInline{Y. A. Malkov and D. A. Yashunin, {``Efficient and robust
approximate nearest neighbor search using hierarchical navigable small
world graphs,''} \emph{IEEE Transactions on Pattern Analysis and Machine
Intelligence}, vol. 42, no. 4, pp. 824--836, 2018.}

\bibitem[\citeproctext]{ref-chromadb2024}
\CSLLeftMargin{{[}19{]} }%
\CSLRightInline{Chroma, {``{ChromaDB}: The open-source embedding
database.''} \url{https://www.trychroma.com/}, 2024.}

\bibitem[\citeproctext]{ref-apa2022dsm5tr}
\CSLLeftMargin{{[}20{]} }%
\CSLRightInline{American Psychiatric Association, \emph{Diagnostic and
statistical manual of mental disorders: {DSM-5-TR}}, 5th Text Revision.
Washington, DC: American Psychiatric Association Publishing, 2022.}

\bibitem[\citeproctext]{ref-chung2022scaling}
\CSLLeftMargin{{[}21{]} }%
\CSLRightInline{{H. W. Chung \emph{et al.}}, {``Scaling
instruction-finetuned language models,''} in \emph{Workshop on large
language models and alignment}, 2022.}

\bibitem[\citeproctext]{ref-touvron2023llama}
\CSLLeftMargin{{[}22{]} }%
\CSLRightInline{{H. Touvron \emph{et al.}}, {``{LLaMA}: Open and
efficient foundation language models,''} in \emph{arXiv preprint
arXiv:2302.13971}, 2023.}

\bibitem[\citeproctext]{ref-team2024gemma}
\CSLLeftMargin{{[}23{]} }%
\CSLRightInline{Gemma Team, {``Gemma: Open models based on {Google}
research and technology,''} \emph{arXiv preprint arXiv:2403.08295},
2024.}

\bibitem[\citeproctext]{ref-rose2020zerotrust}
\CSLLeftMargin{{[}24{]} }%
\CSLRightInline{S. Rose, O. Borchert, S. Mitchell, and S. Connelly,
{``{Zero Trust Architecture},''} {National Institute of Standards and
Technology}; \url{https://doi.org/10.6028/NIST.SP.800-207}, NIST SP
800-207, 2020.}

\bibitem[\citeproctext]{ref-rfc2898}
\CSLLeftMargin{{[}25{]} }%
\CSLRightInline{B. Kaliski, {Internet Engineering Task Force};
\url{https://tools.ietf.org/html/rfc2898}, RFC 2898, 2000.}

\bibitem[\citeproctext]{ref-dworkin2007modes}
\CSLLeftMargin{{[}26{]} }%
\CSLRightInline{M. Dworkin, {``{Recommendation for Block Cipher Modes of
Operation: Galois/Counter Mode ({GCM}) and {GMAC})},''} {National
Institute of Standards and Technology};
\url{https://doi.org/10.6028/NIST.SP.800-38D}, NIST SP 800-38D, 2007.}

\bibitem[\citeproctext]{ref-androidaccessibility2024}
\CSLLeftMargin{{[}27{]} }%
\CSLRightInline{Google, {``{AccessibilityService} \textbar{} {Android}
developers.''}
\url{https://developer.android.com/reference/android/accessibilityservice/AccessibilityService},
2024.}

\bibitem[\citeproctext]{ref-tflite2024}
\CSLLeftMargin{{[}28{]} }%
\CSLRightInline{Google, {``{TensorFlow Lite}: On-device machine learning
framework.''} \url{https://www.tensorflow.org/lite}, 2024.}

\bibitem[\citeproctext]{ref-flutter2024}
\CSLLeftMargin{{[}29{]} }%
\CSLRightInline{Google, {``{Flutter}: Build, ship, and run apps for any
platform.''} \url{https://flutter.dev/}, 2024.}

\bibitem[\citeproctext]{ref-fastapi2024}
\CSLLeftMargin{{[}30{]} }%
\CSLRightInline{S. Ramı́rez, {``{FastAPI}: Modern, fast web framework for
building {APIs} with {Python}.''} \url{https://fastapi.tiangolo.com/},
2024.}

\bibitem[\citeproctext]{ref-supabase2024}
\CSLLeftMargin{{[}31{]} }%
\CSLRightInline{Supabase, {``{Supabase}: The open source {Firebase}
alternative.''} \url{https://supabase.com/}, 2024.}

\bibitem[\citeproctext]{ref-kroenke2002phq9}
\CSLLeftMargin{{[}32{]} }%
\CSLRightInline{K. Kroenke, R. L. Spitzer, and J. B. W. Williams, {``The
{PHQ-9}: Validity of a brief depression severity measure,''}
\emph{Journal of General Internal Medicine}, vol. 16, no. 9, pp.
606--613, 2001.}

\bibitem[\citeproctext]{ref-spitzer2006gad7}
\CSLLeftMargin{{[}33{]} }%
\CSLRightInline{R. L. Spitzer, K. Kroenke, J. B. W. Williams, and B.
Löwe, {``A brief measure for evaluating generalized anxiety disorder:
The {GAD-7},''} \emph{Archives of Internal Medicine}, vol. 166, no. 10,
pp. 1092--1097, 2006.}

\bibitem[\citeproctext]{ref-dettmers2022qlora}
\CSLLeftMargin{{[}34{]} }%
\CSLRightInline{T. Dettmers, A. Pagnoni, A. Holtzman, and L.
Zettlemoyer, {``{QLoRA}: Efficient fine-tuning of quantized large
language models,''} \emph{arXiv preprint arXiv:2305.14314}, 2023.}

\end{CSLReferences}




\end{document}
